// =================================================================
// FACULTY_DATA.JS — KL UNIVERSITY (KLEF)
// MITRA — Emotion-Aware Student AI
// Author: Lokesh Manepalli | Roll: 2300031647 | CSE 2023-2027
// =================================================================
// NOTE: FAC_DATA is moved HERE from index.html
// index.html should have: <script src="faculty_data.js"></script>
// =================================================================

const FAC_DATA = [
  // AGRICULTURE - KLV
  {name:"Dr. Ratna Prasad Pavuluri",role:"PROFESSOR",dept:"Agriculture",campus:"KLV"},
  {name:"Dr. Senthilmurugan P",role:"ASSOC.PROF.",dept:"Agriculture",campus:"KLV"},
  {name:"Mr. Jamindar Buddiga",role:"ASSOC.PROF.",dept:"Agriculture",campus:"KLV"},
  {name:"Dr. Bontu Bala Krishna",role:"ASST.PROF.",dept:"Agriculture",campus:"KLV"},
  {name:"Dr. Manoharmayum Dolpriya Devi",role:"ASST.PROF.",dept:"Agriculture",campus:"KLV"},
  {name:"Dr. Atul Singh",role:"ASST.PROF.",dept:"Agriculture",campus:"KLV"},
  {name:"Dr. Shivasai Prasad",role:"ASST.PROF.",dept:"Agriculture",campus:"KLV"},
  {name:"Dr. Bonu Rama Devi",role:"ASST.PROF.",dept:"Agriculture",campus:"KLV"},
  {name:"Dr. M Gayathri",role:"ASST.PROF.",dept:"Agriculture",campus:"KLV"},
  {name:"Dr. Maddirala Surendra Babu",role:"ASST.PROF.",dept:"Agriculture",campus:"KLV"},
  {name:"Dr. Sravani Dumala",role:"ASST.PROF.",dept:"Agriculture",campus:"KLV"},
  {name:"Dr. Prince Jayasimha Pamala",role:"ASST.PROF.",dept:"Agriculture",campus:"KLV"},
  {name:"Dr. Nukasani Sagarika",role:"ASST.PROF.",dept:"Agriculture",campus:"KLV"},
  {name:"Dr. Md Abdul Basith",role:"ASST.PROF.",dept:"Agriculture",campus:"KLV"},
  {name:"Dr. Ashok Kumar",role:"ASST.PROF.",dept:"Agriculture",campus:"KLV"},
  {name:"Dr. Monoj Sutradhar",role:"ASST.PROF.",dept:"Agriculture",campus:"KLV"},
  {name:"Dr. Sivanand Parashuram Yarazari",role:"ASST.PROF.",dept:"Agriculture",campus:"KLV"},
  {name:"Dr. Valluri Jhansi Hima Varsha",role:"ASST.PROF.",dept:"Agriculture",campus:"KLV"},
  {name:"Dr. Jujjavarapu Rama Rajeshwar",role:"ASST.PROF.",dept:"Agriculture",campus:"KLV"},
  {name:"Dr. Narayanappa Prabhavathi",role:"ASST.PROF.",dept:"Agriculture",campus:"KLV"},
  {name:"Dr. Verella Ragamalika",role:"ASST.PROF.",dept:"Agriculture",campus:"KLV"},
  {name:"Dr. Bathineni Vibhajam Sagal Kiran",role:"ASST.PROF.",dept:"Agriculture",campus:"KLV"},
  {name:"Dr. Pilla Avinash",role:"ASST.PROF.",dept:"Agriculture",campus:"KLV"},
  {name:"Dr. Kommalapati Beaulah Glory",role:"ASST.PROF.",dept:"Agriculture",campus:"KLV"},
  {name:"Ms. Pilli Manasa",role:"ASST.PROF.",dept:"Agriculture",campus:"KLV"},
  // ARCHITECTURE - KLV
  {name:"Mr. Shaik Sami Ur Rehman",role:"PROFESSOR",dept:"Architecture",campus:"KLV"},
  {name:"Ms. Adhikesavalu Priya",role:"ASSOC.PROF.",dept:"Architecture",campus:"KLV"},
  {name:"Ms. Tanushree Das",role:"ASSOC.PROF.",dept:"Architecture",campus:"KLV"},
  {name:"Mr. Bonda Kiran Kumar",role:"ASSOC.PROF.",dept:"Architecture",campus:"KLV"},
  {name:"Ms. Kavuri Venkata Lakshmi",role:"ASSOC.PROF.",dept:"Architecture",campus:"KLV"},
  {name:"Mr. Shivendu Shekhar Singh",role:"ASST.PROF.",dept:"Architecture",campus:"KLV"},
  {name:"Ar. Senthil Kumar P",role:"ASST.PROF.",dept:"Architecture",campus:"KLV"},
  {name:"Mr. Itta Rudra Murthy",role:"ASST.PROF.",dept:"Architecture",campus:"KLV"},
  {name:"Ms. Harshitha Kuntamukkala",role:"ASST.PROF.",dept:"Architecture",campus:"KLV"},
  {name:"Ms. Gopika Girissan",role:"ASST.PROF.",dept:"Architecture",campus:"KLV"},
  {name:"Ms. Vishnu Priya Balanagarajan",role:"ASST.PROF.",dept:"Architecture",campus:"KLV"},
  {name:"Ms. Lanka Virajitha",role:"ASST.PROF.",dept:"Architecture",campus:"KLV"},
  {name:"Dr. Metta Achyutha Kumar Reddy",role:"ASST.PROF.",dept:"Architecture",campus:"KLV"},
  {name:"Mr. Kanneganti Jyothishya Brahma Chari",role:"ASST.PROF.",dept:"Architecture",campus:"KLV"},
  // ARTS - KLV
  {name:"Dr. Rudrabhatla Sai Kumar",role:"ASSOC.PROF.",dept:"Arts",campus:"KLV"},
  {name:"Dr. Kukkamalla Anil Kumar",role:"ASST.PROF.",dept:"Arts",campus:"KLV"},
  {name:"Dr. Gunna Venkateswarlu",role:"ASST.PROF.",dept:"Arts",campus:"KLV"},
  {name:"Dr. Kantam Rajesh Kumar",role:"ASST.PROF.",dept:"Arts",campus:"KLV"},
  // BIOTECHNOLOGY - KLV
  {name:"Dr. B Jayakumar Singh",role:"PROFESSOR",dept:"Biotechnology",campus:"KLV"},
  {name:"Dr. Kamma Srinivasulu",role:"PROFESSOR",dept:"Biotechnology",campus:"KLV"},
  {name:"Dr. Burra Venkata Laxmi Siva Prasad",role:"PROFESSOR",dept:"Biotechnology",campus:"KLV"},
  {name:"Dr. M Janaki Ramaiah",role:"PROFESSOR",dept:"Biotechnology",campus:"KLV"},
  {name:"Dr. Vemuri Praveen Kumar",role:"ASSOC.PROF.",dept:"Biotechnology",campus:"KLV"},
  {name:"Dr. Nadeem Siddiqui",role:"ASSOC.PROF.",dept:"Biotechnology",campus:"KLV"},
  {name:"Dr. Ashish Runthala",role:"ASSOC.PROF.",dept:"Biotechnology",campus:"KLV"},
  {name:"Dr. Bandaru Srinivas",role:"ASSOC.PROF.",dept:"Biotechnology",campus:"KLV"},
  {name:"Dr. E S Sharmila Sigamany",role:"ASSOC.PROF.",dept:"Biotechnology",campus:"KLV"},
  {name:"Dr. Muddada Sudhamani",role:"ASSOC.PROF.",dept:"Biotechnology",campus:"KLV"},
  {name:"Dr. S V Subrahmanyam",role:"ASSOC.PROF.",dept:"Biotechnology",campus:"KLV"},
  {name:"Dr. N Vedavathi",role:"ASSOC.PROF.",dept:"Biotechnology",campus:"KLV"},
  {name:"Dr. Mallu Maheswara Reddy",role:"ASST.PROF.",dept:"Biotechnology",campus:"KLV"},
  {name:"Dr. Golamari Siva Reddy",role:"ASST.PROF.",dept:"Biotechnology",campus:"KLV"},
  {name:"Dr. Pinnamaneni Rajasekhar",role:"ASST.PROF.",dept:"Biotechnology",campus:"KLV"},
  {name:"Dr. Chanda Chandrasekhar",role:"ASST.PROF.",dept:"Biotechnology",campus:"KLV"},
  {name:"Dr. Yella Venkata Rajesh",role:"ASST.PROF.",dept:"Biotechnology",campus:"KLV"},
  {name:"Dr. Sarada Prasanna Mallick",role:"ASST.PROF.",dept:"Biotechnology",campus:"KLV"},
  {name:"Dr. Gujjula Koteswara Reddy",role:"ASST.PROF.",dept:"Biotechnology",campus:"KLV"},
  {name:"Dr. Pritam Kumar Dikshit",role:"ASST.PROF.",dept:"Biotechnology",campus:"KLV"},
  {name:"Dr. Kola Hemamalini",role:"ASST.PROF.",dept:"Biotechnology",campus:"KLV"},
  {name:"Dr. Ashish Appasaheb Kadam",role:"ASST.PROF.",dept:"Biotechnology",campus:"KLV"},
  // BUSINESS SCHOOL - KLV
  {name:"Dr. Marivina Kishore Babu",role:"PROFESSOR",dept:"Business School",campus:"KLV"},
  {name:"Dr. Venkateswara Rao Podile",role:"PROFESSOR",dept:"Business School",campus:"KLV"},
  {name:"Dr. Marimganti Srinivasa Narayana",role:"PROFESSOR",dept:"Business School",campus:"KLV"},
  {name:"Dr. N Subrahmanyam",role:"PROFESSOR",dept:"Business School",campus:"KLV"},
  {name:"Dr. Atanu Talukdar",role:"PROFESSOR",dept:"Business School",campus:"KLV"},
  {name:"Dr. Radha Krishan Sharma",role:"PROFESSOR",dept:"Business School",campus:"KLV"},
  {name:"Dr. Vadapalli Ravindhar",role:"PROFESSOR",dept:"Business School",campus:"KLV"},
  {name:"Dr. Kodukula S L N S Subrahmanyam",role:"ASSOC.PROF.",dept:"Business School",campus:"KLV"},
  {name:"Dr. Subramanyam Mamidala",role:"ASSOC.PROF.",dept:"Business School",campus:"KLV"},
  {name:"Dr. Robert Edwin Chester Jhonson",role:"ASSOC.PROF.",dept:"Business School",campus:"KLV"},
  {name:"Dr. Srinivasa Rao Kasisomayajula",role:"ASSOC.PROF.",dept:"Business School",campus:"KLV"},
  {name:"Dr. K Hema Divya",role:"ASSOC.PROF.",dept:"Business School",campus:"KLV"},
  {name:"Dr. K S Venkateswara Kumar",role:"ASSOC.PROF.",dept:"Business School",campus:"KLV"},
  {name:"Dr. Atluri Bala Saraswathi",role:"ASSOC.PROF.",dept:"Business School",campus:"KLV"},
  {name:"Dr. Simanchala Das",role:"ASSOC.PROF.",dept:"Business School",campus:"KLV"},
  {name:"Dr. Kolachina Srinivas",role:"ASSOC.PROF.",dept:"Business School",campus:"KLV"},
  {name:"Dr. Savanam Chandra Sekhar",role:"ASSOC.PROF.",dept:"Business School",campus:"KLV"},
  {name:"Dr. Gowrabhathini Jitendra",role:"ASSOC.PROF.",dept:"Business School",campus:"KLV"},
  {name:"Dr. Domathoti Prasanna Kumar",role:"ASSOC.PROF.",dept:"Business School",campus:"KLV"},
  {name:"Dr. A Uday Shankar",role:"ASSOC.PROF.",dept:"Business School",campus:"KLV"},
  {name:"Dr. V N Sailaja",role:"ASSOC.PROF.",dept:"Business School",campus:"KLV"},
  {name:"Dr. Narayanam Bindu Madhavi",role:"ASSOC.PROF.",dept:"Business School",campus:"KLV"},
  {name:"Dr. Sundari Dadhabai",role:"ASSOC.PROF.",dept:"Business School",campus:"KLV"},
  {name:"Dr. Akondi Srikanth",role:"ASSOC.PROF.",dept:"Business School",campus:"KLV"},
  {name:"Dr. Sontineni Ramesh Babu",role:"ASSOC.PROF.",dept:"Business School",campus:"KLV"},
  {name:"Dr. Rajendran P",role:"ASSOC.PROF.",dept:"Business School",campus:"KLV"},
  {name:"Dr. M V A L Narasimha Rao",role:"ASSOC.PROF.",dept:"Business School",campus:"KLV"},
  {name:"Dr. Venkata Ramana Sikhakolli",role:"ASSOC.PROF.",dept:"Business School",campus:"KLV"},
  {name:"Dr. Sukhavasi Santha Kumari",role:"ASST.PROF.",dept:"Business School",campus:"KLV"},
  {name:"Dr. Sonti Venkata Nagamalleswara Sastry",role:"ASST.PROF.",dept:"Business School",campus:"KLV"},
  {name:"Dr. Itikela Shyam Sundar",role:"ASST.PROF.",dept:"Business School",campus:"KLV"},
  {name:"Dr. Nagala Shyam Venkata Nooka Raju",role:"ASST.PROF.",dept:"Business School",campus:"KLV"},
  {name:"Dr. Debadatta Das",role:"ASST.PROF.",dept:"Business School",campus:"KLV"},
  {name:"Dr. Arumugam Raju",role:"ASST.PROF.",dept:"Business School",campus:"KLV"},
  {name:"Dr. Romala Vijaya Srinivas",role:"ASST.PROF.",dept:"Business School",campus:"KLV"},
  {name:"Dr. R Pradeep Kumar Patnaik",role:"ASST.PROF.",dept:"Business School",campus:"KLV"},
  {name:"Dr. Kalla V Bangaru Ganesh",role:"ASST.PROF.",dept:"Business School",campus:"KLV"},
  {name:"Dr. Parvathaneni Krishna Priya",role:"ASST.PROF.",dept:"Business School",campus:"KLV"},
  {name:"Dr. Sabbineni Poojitha",role:"ASST.PROF.",dept:"Business School",campus:"KLV"},
  {name:"Dr. Anuradha Averineni",role:"ASST.PROF.",dept:"Business School",campus:"KLV"},
  {name:"Dr. Navulla Durga Prasad",role:"ASST.PROF.",dept:"Business School",campus:"KLV"},
  {name:"Dr. Mudit Saxena",role:"ASST.PROF.",dept:"Business School",campus:"KLV"},
  {name:"Dr. J Venkata Ramana",role:"ASST.PROF.",dept:"Business School",campus:"KLV"},
  {name:"Dr. Ch Balaji",role:"ASST.PROF.",dept:"Business School",campus:"KLV"},
  {name:"Dr. K Anusha",role:"ASST.PROF.",dept:"Business School",campus:"KLV"},
  {name:"Dr. K V Siva Prasad",role:"ASST.PROF.",dept:"Business School",campus:"KLV"},
  {name:"Dr. R S V Rama Swathi",role:"ASST.PROF.",dept:"Business School",campus:"KLV"},
  {name:"Dr. R Kanimozhi",role:"ASST.PROF.",dept:"Business School",campus:"KLV"},
  {name:"Dr. Burra Vamsi Krishna",role:"ASST.PROF.",dept:"Business School",campus:"KLV"},
  {name:"Dr. Daniel Pilli",role:"ASST.PROF.",dept:"Business School",campus:"KLV"},
  {name:"Dr. Taddi Venkata Siva Santoshi Swathi",role:"ASST.PROF.",dept:"Business School",campus:"KLV"},
  {name:"Mr. Umesh Kumar Shukla",role:"ASST.PROF.",dept:"Business School",campus:"KLV"},
  {name:"Mr. A Jagdish Mohan Rao",role:"ASST.PROF.",dept:"Business School",campus:"KLV"},
  // CHEMISTRY - KLV
  {name:"Dr. Kottapalli Raja Sekhara Prasad",role:"PROFESSOR",dept:"Chemistry",campus:"KLV"},
  {name:"Dr. V Shanmukhkumar Jagarlapudi",role:"PROFESSOR",dept:"Chemistry",campus:"KLV"},
  {name:"Dr. Pradeep Kumar Brahman",role:"ASSOC.PROF.",dept:"Chemistry",campus:"KLV"},
  {name:"Dr. M Radha Madhavi",role:"ASSOC.PROF.",dept:"Chemistry",campus:"KLV"},
  {name:"Dr. Anna Venkateswara Rao",role:"ASST.PROF.",dept:"Chemistry",campus:"KLV"},
  // CIVIL ENGINEERING - KLV
  {name:"Dr. A V S Prasad",role:"PROFESSOR",dept:"Civil Engineering",campus:"KLV"},
  {name:"Dr. Chappidi Hanumantha Rao",role:"PROFESSOR",dept:"Civil Engineering",campus:"KLV"},
  {name:"Dr. Palleboina Poluraju",role:"PROFESSOR",dept:"Civil Engineering",campus:"KLV"},
  {name:"Dr. A Aravindan",role:"PROFESSOR",dept:"Civil Engineering",campus:"KLV"},
  {name:"Dr. Sanjeet Kumar",role:"ASSOC.PROF.",dept:"Civil Engineering",campus:"KLV"},
  {name:"Dr. Ashwin Narendra Raut",role:"ASSOC.PROF.",dept:"Civil Engineering",campus:"KLV"},
  {name:"Dr. Jagarapu Durga Chaitanya Kumar",role:"ASST.PROF.",dept:"Civil Engineering",campus:"KLV"},
  {name:"Dr. Lingeshwaran N",role:"ASST.PROF.",dept:"Civil Engineering",campus:"KLV"},
  {name:"Dr. Anu Mary Ealias",role:"ASST.PROF.",dept:"Civil Engineering",campus:"KLV"},
  {name:"Mr. K Syam Chambrelin",role:"ASST.PROF.",dept:"Civil Engineering",campus:"KLV"},
  {name:"Mr. Kommineni Hemanth Raja",role:"ASST.PROF.",dept:"Civil Engineering",campus:"KLV"},
  {name:"Mr. Bodapati Gnana Rahul",role:"ASST.PROF.",dept:"Civil Engineering",campus:"KLV"},
  // COMPUTER APPLICATIONS - KLV
  {name:"Dr. Kodukula Subrahmanyam",role:"PROFESSOR",dept:"Computer Applications",campus:"KLV"},
  {name:"Dr. G Krishna Mohan",role:"PROFESSOR",dept:"Computer Applications",campus:"KLV"},
  {name:"Dr. Kothamasu Kiran Kumar",role:"PROFESSOR",dept:"Computer Applications",campus:"KLV"},
  {name:"Dr. Chetty Manna Sheela Rani",role:"PROFESSOR",dept:"Computer Applications",campus:"KLV"},
  {name:"Dr. V Valli Mayil",role:"PROFESSOR",dept:"Computer Applications",campus:"KLV"},
  {name:"Dr. R D Sathiya",role:"PROFESSOR",dept:"Computer Applications",campus:"KLV"},
  {name:"Dr. V S Bhagavan",role:"PROFESSOR",dept:"Computer Applications",campus:"KLV"},
  {name:"Dr. Movva Naga Venkata Kiran Babu",role:"ASSOC.PROF.",dept:"Computer Applications",campus:"KLV"},
  {name:"Dr. Bandarupalli Mouleswara Rao",role:"ASSOC.PROF.",dept:"Computer Applications",campus:"KLV"},
  {name:"Dr. Arulswamy Sivaramakrishnan",role:"ASSOC.PROF.",dept:"Computer Applications",campus:"KLV"},
  {name:"Dr. Venkata Surya Narayana Tinnaluri",role:"ASSOC.PROF.",dept:"Computer Applications",campus:"KLV"},
  {name:"Dr. Potluri Venkata Hari Prasad",role:"ASSOC.PROF.",dept:"Computer Applications",campus:"KLV"},
  {name:"Dr. Ch Madhava Rao",role:"ASSOC.PROF.",dept:"Computer Applications",campus:"KLV"},
  {name:"Dr. Karamala Himabindu",role:"ASSOC.PROF.",dept:"Computer Applications",campus:"KLV"},
  {name:"Dr. Konduri Bhagavan",role:"ASSOC.PROF.",dept:"Computer Applications",campus:"KLV"},
  {name:"Dr. Mutyaboyina Latha",role:"ASSOC.PROF.",dept:"Computer Applications",campus:"KLV"},
  {name:"Dr. Munagala Madhu Sudhan Rao",role:"ASSOC.PROF.",dept:"Computer Applications",campus:"KLV"},
  {name:"Dr. Talagadadevi Srinivasa Rao",role:"ASSOC.PROF.",dept:"Computer Applications",campus:"KLV"},
  {name:"Dr. Nerella Srimannarayana",role:"ASSOC.PROF.",dept:"Computer Applications",campus:"KLV"},
  {name:"Dr. Venkateswarlu Gundu",role:"ASST.PROF.",dept:"Computer Applications",campus:"KLV"},
  {name:"Dr. Taushif Anwar",role:"ASST.PROF.",dept:"Computer Applications",campus:"KLV"},
  {name:"Dr. Jeevan Jala",role:"ASST.PROF.",dept:"Computer Applications",campus:"KLV"},
  {name:"Mr. Rama Krishna Yellapragada",role:"ASST.PROF.",dept:"Computer Applications",campus:"KLV"},
  {name:"Mr. Nadakuduru Venkata Ramana",role:"ASST.PROF.",dept:"Computer Applications",campus:"KLV"},
  {name:"Mr. Ghufran Ahmad Khan",role:"ASST.PROF.",dept:"Computer Applications",campus:"KLV"},
  {name:"Mr. Zulfikar Ali Ansari",role:"ASST.PROF.",dept:"Computer Applications",campus:"KLV"},
  {name:"Ms. Bhargavi Mopuru",role:"ASST.PROF.",dept:"Computer Applications",campus:"KLV"},
  {name:"Mr. Gobinda Chandra Das",role:"ASST.PROF.",dept:"Computer Applications",campus:"KLV"},
  {name:"Mr. Nagendra Babu Rajaboina",role:"ASST.PROF.",dept:"Computer Applications",campus:"KLV"},
  {name:"Mr. Angalkuditi Srinivas",role:"ASST.PROF.",dept:"Computer Applications",campus:"KLV"},
  {name:"Mr. Choutapalli Nagaraju",role:"ASST.PROF.",dept:"Computer Applications",campus:"KLV"},
  {name:"Ms. Thonepudi Hemalatha",role:"ASST.PROF.",dept:"Computer Applications",campus:"KLV"},
  {name:"Mr. Chintamaneni Phanikanth",role:"ASST.PROF.",dept:"Computer Applications",campus:"KLV"},
  {name:"Ms. Chalamalasetty Sravani",role:"ASST.PROF.",dept:"Computer Applications",campus:"KLV"},
  {name:"Mr. Asok Kumar Rathinam",role:"ASST.PROF.",dept:"Computer Applications",campus:"KLV"},
  {name:"Mr. Pallabothula Ramesh",role:"ASST.PROF.",dept:"Computer Applications",campus:"KLV"},
  {name:"Mr. D Surendra",role:"ASST.PROF.",dept:"Computer Applications",campus:"KLV"},
  {name:"Ms. Ch Satya Keerthi N V L",role:"ASST.PROF.",dept:"Computer Applications",campus:"KLV"},
  {name:"Mr. Lingidi Nageswar Rao",role:"ASST.PROF.",dept:"Computer Applications",campus:"KLV"},
  {name:"Ms. Borra Vishnupriya",role:"ASST.PROF.",dept:"Computer Applications",campus:"KLV"},
  {name:"Mr. A Prathap",role:"ASST.PROF.",dept:"Computer Applications",campus:"KLV"},
  {name:"Mr. A Siddhartha Reddy",role:"ASST.PROF.",dept:"Computer Applications",campus:"KLV"},
  {name:"Mr. G Bala Venkata Kishore",role:"ASST.PROF.",dept:"Computer Applications",campus:"KLV"},
  {name:"Dr. A Priyadharshini",role:"ASST.PROF.",dept:"Computer Applications",campus:"KLV"},
  {name:"Mr. Subhash Chandra Yalavarthy",role:"ASST.PROF.",dept:"Computer Applications",campus:"KLV"},
  {name:"Dr. Vurity Mounika",role:"ASST.PROF.",dept:"Computer Applications",campus:"KLV"},
  // CSE - KLV (Professors)
  {name:"Dr. Gandharba Swain",role:"PROFESSOR",dept:"CSE",campus:"KLV"},
  {name:"Dr. Vijaya Lakshmi P",role:"PROFESSOR",dept:"CSE",campus:"KLV"},
  {name:"Dr. Vishnubhotla Rama Krishna",role:"PROFESSOR",dept:"CSE",campus:"KLV"},
  {name:"Dr. Adapa Srinivasa Rao",role:"PROFESSOR",dept:"CSE",campus:"KLV"},
  {name:"Dr. Gottumukkala P Saradhi Varma",role:"PROFESSOR",dept:"CSE",campus:"KLV"},
  {name:"Dr. Tirumala Kodanda Rama Krishna Rao",role:"PROFESSOR",dept:"CSE",campus:"KLV"},
  {name:"Dr. Vemuru Srikanth",role:"PROFESSOR",dept:"CSE",campus:"KLV"},
  {name:"Dr. Senthil Athithan",role:"PROFESSOR",dept:"CSE",campus:"KLV"},
  {name:"Dr. Tummala Pavan Kumar",role:"PROFESSOR",dept:"CSE",campus:"KLV"},
  {name:"Dr. Yalla Prasanth",role:"PROFESSOR",dept:"CSE",campus:"KLV"},
  {name:"Dr. Kasula Venkata Durga Kiran",role:"PROFESSOR",dept:"CSE",campus:"KLV"},
  {name:"Dr. Malladi Srinivas",role:"PROFESSOR",dept:"CSE",campus:"KLV"},
  {name:"Dr. Burra Vijay Babu",role:"PROFESSOR",dept:"CSE",campus:"KLV"},
  {name:"Dr. Gajula Siva Nageswara Rao",role:"PROFESSOR",dept:"CSE",campus:"KLV"},
  {name:"Dr. Kallipalli Venkata Raju",role:"PROFESSOR",dept:"CSE",campus:"KLV"},
  {name:"Dr. Kopparti V V Satyanarayana",role:"PROFESSOR",dept:"CSE",campus:"KLV"},
  {name:"Dr. Nulaka Srinivasu",role:"PROFESSOR",dept:"CSE",campus:"KLV"},
  {name:"Dr. P V R D Prasada Rao",role:"PROFESSOR",dept:"CSE",campus:"KLV"},
  {name:"Dr. Gera Pradeepini",role:"PROFESSOR",dept:"CSE",campus:"KLV"},
  {name:"Dr. Pothuraju Raja Rajeswari",role:"PROFESSOR",dept:"CSE",campus:"KLV"},
  {name:"Dr. Shaik Sagar Imambi",role:"PROFESSOR",dept:"CSE",campus:"KLV"},
  {name:"Dr. Mohammed Moulana",role:"PROFESSOR",dept:"CSE",campus:"KLV"},
  {name:"Dr. Kolla Bhanu Prakash",role:"PROFESSOR",dept:"CSE",campus:"KLV"},
  {name:"Dr. Enireddy Vamsidhar",role:"PROFESSOR",dept:"CSE",campus:"KLV"},
  {name:"Dr. Tatavarthy Santhi Sri",role:"PROFESSOR",dept:"CSE",campus:"KLV"},
  {name:"Dr. A K Velmurugan",role:"PROFESSOR",dept:"CSE",campus:"KLV"},
  {name:"Dr. Moparthi Nageswara Rao",role:"PROFESSOR",dept:"CSE",campus:"KLV"},
  {name:"Dr. Vithya Ganesan",role:"PROFESSOR",dept:"CSE",campus:"KLV"},
  {name:"Dr. Bhukya Srinivasa Arao",role:"PROFESSOR",dept:"CSE",campus:"KLV"},
  {name:"Dr. Debnath Bhattacharyya",role:"PROFESSOR",dept:"CSE",campus:"KLV"},
  {name:"Dr. Suryakanth V Gangashetty",role:"PROFESSOR",dept:"CSE",campus:"KLV"},
  {name:"Dr. Govind Divakaran",role:"PROFESSOR",dept:"CSE",campus:"KLV"},
  {name:"Dr. Sandeep Kumar Sahratia",role:"PROFESSOR",dept:"CSE",campus:"KLV"},
  {name:"Dr. Viswanathan Ramasamy",role:"PROFESSOR",dept:"CSE",campus:"KLV"},
  {name:"Dr. Kandepu Bala Venkata Brahmarao",role:"PROFESSOR",dept:"CSE",campus:"KLV"},
  {name:"Dr. Yogesh Kumar Sharma",role:"PROFESSOR",dept:"CSE",campus:"KLV"},
  {name:"Dr. V Murugesh",role:"PROFESSOR",dept:"CSE",campus:"KLV"},
  {name:"Dr. Manoj Wadhwa",role:"PROFESSOR",dept:"CSE",campus:"KLV"},
  {name:"Dr. Arpit Jain",role:"PROFESSOR",dept:"CSE",campus:"KLV"},
  {name:"Dr. Leena Arya",role:"PROFESSOR",dept:"CSE",campus:"KLV"},
  {name:"Dr. Ravi Rastogi",role:"PROFESSOR",dept:"CSE",campus:"KLV"},
  {name:"Dr. Dara Vikram",role:"PROFESSOR",dept:"CSE",campus:"KLV"},
  {name:"Dr. Smitha Chowdary",role:"PROFESSOR",dept:"CSE",campus:"KLV"},
  {name:"Dr. Bobba Veeramallu",role:"PROFESSOR",dept:"CSE",campus:"KLV"},
  {name:"Dr. V Viswanath Shenoi",role:"PROFESSOR",dept:"CSE",campus:"KLV"},
  {name:"Dr. Rajendra Kumar Ganiya",role:"PROFESSOR",dept:"CSE",campus:"KLV"},
  {name:"Dr. Dharmaiah Devarapalli",role:"PROFESSOR",dept:"CSE",campus:"KLV"},
  {name:"Dr. D Haritha",role:"PROFESSOR",dept:"CSE",campus:"KLV"},
  {name:"Dr. N Alangudi Balaji",role:"PROFESSOR",dept:"CSE",campus:"KLV"},
  {name:"Dr. Kommu Siddhardha Mavo Vara Kumar",role:"PROFESSOR",dept:"CSE",campus:"KLV"},
  {name:"Dr. Kothalanka Amarendra",role:"PROFESSOR",dept:"CSE",campus:"KLV"},
  {name:"Dr. Ganga Rama Koteswara Rao",role:"PROFESSOR",dept:"CSE",campus:"KLV"},
  {name:"Dr. Mohammed Ali Hussain",role:"PROFESSOR",dept:"CSE",campus:"KLV"},
  {name:"Dr. Manchiraju Kameswara Rao",role:"PROFESSOR",dept:"CSE",campus:"KLV"},
  {name:"Dr. Mathews Sandra Carmel Sophia",role:"PROFESSOR",dept:"CSE",campus:"KLV"},
  {name:"Dr. Gurrampati Venkata Ramana Reddy",role:"PROFESSOR",dept:"CSE",campus:"KLV"},
  {name:"Dr. Ch V Ramana Murthy",role:"PROFESSOR",dept:"CSE",campus:"KLV"},
  // CSE - KLV (Assoc Profs)
  {name:"Dr. Tiruveedhula Sajana",role:"ASSOC.PROF.",dept:"CSE",campus:"KLV"},
  {name:"Dr. Jagjit Singh Dhatterwal",role:"ASSOC.PROF.",dept:"CSE",campus:"KLV"},
  {name:"Dr. Elangovan Guruva Reddy",role:"ASSOC.PROF.",dept:"CSE",campus:"KLV"},
  {name:"Dr. Sunitha Pachala",role:"ASSOC.PROF.",dept:"CSE",campus:"KLV"},
  {name:"Dr. Bolla Sreenivasulu",role:"ASSOC.PROF.",dept:"CSE",campus:"KLV"},
  {name:"Dr. A Hanumanth",role:"ASSOC.PROF.",dept:"CSE",campus:"KLV"},
  {name:"Dr. Bolleddu Siva Nagaiah",role:"ASSOC.PROF.",dept:"CSE",campus:"KLV"},
  {name:"Dr. Niranjan Patra",role:"ASSOC.PROF.",dept:"CSE",campus:"KLV"},
  {name:"Mr. Hari Kiran Vege",role:"ASSOC.PROF.",dept:"CSE",campus:"KLV"},
  {name:"Dr. Boddu Sekhar Babu",role:"ASSOC.PROF.",dept:"CSE",campus:"KLV"},
  {name:"Dr. Chintala Radhika Rani",role:"ASSOC.PROF.",dept:"CSE",campus:"KLV"},
  {name:"Dr. Sabbineni Srinivasa Rao",role:"ASSOC.PROF.",dept:"CSE",campus:"KLV"},
  {name:"Dr. Venkata Vara Prasad Padyala",role:"ASSOC.PROF.",dept:"CSE",campus:"KLV"},
  {name:"Dr. Anne V Praveen Krishna",role:"ASSOC.PROF.",dept:"CSE",campus:"KLV"},
  {name:"Dr. K Ruth Ramya",role:"ASSOC.PROF.",dept:"CSE",campus:"KLV"},
  {name:"Dr. P Lakshmi Prasanna",role:"ASSOC.PROF.",dept:"CSE",campus:"KLV"},
  {name:"Dr. K Ravindranadh",role:"ASSOC.PROF.",dept:"CSE",campus:"KLV"},
  {name:"Dr. Bondalapu Chaitanya Krishna",role:"ASSOC.PROF.",dept:"CSE",campus:"KLV"},
  {name:"Dr. Peddada Venkateswara Rao",role:"ASSOC.PROF.",dept:"CSE",campus:"KLV"},
  {name:"Dr. Tata Ravi Kumar",role:"ASSOC.PROF.",dept:"CSE",campus:"KLV"},
  {name:"Dr. Dubba Nagamalleswari",role:"ASSOC.PROF.",dept:"CSE",campus:"KLV"},
  {name:"Dr. Vurukonda Naresh",role:"ASSOC.PROF.",dept:"CSE",campus:"KLV"},
  {name:"Dr. Pydimarri Venkata Ravi Kumar",role:"ASSOC.PROF.",dept:"CSE",campus:"KLV"},
  {name:"Dr. Venkata Naresh Mandhala",role:"ASSOC.PROF.",dept:"CSE",campus:"KLV"},
  {name:"Dr. Gogineni Krishna Chaitanya",role:"ASSOC.PROF.",dept:"CSE",campus:"KLV"},
  {name:"Dr. Maguluri Lakshmana Phaneendra",role:"ASSOC.PROF.",dept:"CSE",campus:"KLV"},
  {name:"Dr. Modepalli Kavitha",role:"ASSOC.PROF.",dept:"CSE",campus:"KLV"},
  {name:"Dr. Rachapudi Venubabu",role:"ASSOC.PROF.",dept:"CSE",campus:"KLV"},
  {name:"Dr. Raju Anitha",role:"ASSOC.PROF.",dept:"CSE",campus:"KLV"},
  {name:"Dr. Pachipala Yellamma",role:"ASSOC.PROF.",dept:"CSE",campus:"KLV"},
  {name:"Dr. Kinjirapu Ashesh",role:"ASSOC.PROF.",dept:"CSE",campus:"KLV"},
  {name:"Dr. Swarna Kuchibhotla",role:"ASSOC.PROF.",dept:"CSE",campus:"KLV"},
  {name:"Dr. Pellakuri Vidyullatha",role:"ASSOC.PROF.",dept:"CSE",campus:"KLV"},
  {name:"Dr. Mothukuri Radha",role:"ASSOC.PROF.",dept:"CSE",campus:"KLV"},
  {name:"Dr. Dinesh Kumar A",role:"ASSOC.PROF.",dept:"CSE",campus:"KLV"},
  {name:"Dr. C Karthikeyan",role:"ASSOC.PROF.",dept:"CSE",campus:"KLV"},
  {name:"Dr. Tumuluru Praveen",role:"ASSOC.PROF.",dept:"CSE",campus:"KLV"},
  {name:"Dr. Nikhat Parveen",role:"ASSOC.PROF.",dept:"CSE",campus:"KLV"},
  {name:"Dr. Arvind Yadav",role:"ASSOC.PROF.",dept:"CSE",campus:"KLV"},
  {name:"Dr. Padmanaban K",role:"ASSOC.PROF.",dept:"CSE",campus:"KLV"},
  {name:"Dr. Kunda Venkata Prasad",role:"ASSOC.PROF.",dept:"CSE",campus:"KLV"},
  {name:"Dr. Vijay Kumar Burugari",role:"ASSOC.PROF.",dept:"CSE",campus:"KLV"},
  {name:"Dr. Nallagatla Raghavendra Sai",role:"ASSOC.PROF.",dept:"CSE",campus:"KLV"},
  {name:"Dr. P M Ashok Kumar",role:"ASSOC.PROF.",dept:"CSE",campus:"KLV"},
  {name:"Dr. Vidya Sagar Ponnam",role:"ASSOC.PROF.",dept:"CSE",campus:"KLV"},
  {name:"Dr. A Abdul Rahman",role:"ASSOC.PROF.",dept:"CSE",campus:"KLV"},
  {name:"Dr. Veerubhotla Siva Rama Krishna Sharma",role:"ASSOC.PROF.",dept:"CSE",campus:"KLV"},
  {name:"Dr. Veerraju Gampala",role:"ASSOC.PROF.",dept:"CSE",campus:"KLV"},
  {name:"Dr. Shankar Rajendran",role:"ASSOC.PROF.",dept:"CSE",campus:"KLV"},
  {name:"Dr. Murali Mohan Vutukuru",role:"ASSOC.PROF.",dept:"CSE",campus:"KLV"},
  {name:"Dr. Sadam Kavitha",role:"ASSOC.PROF.",dept:"CSE",campus:"KLV"},
  {name:"Dr. Sangaraju Hrushikesava Raju",role:"ASSOC.PROF.",dept:"CSE",campus:"KLV"},
  {name:"Dr. Nilu Singh",role:"ASSOC.PROF.",dept:"CSE",campus:"KLV"},
  {name:"Dr. P Ithaya Rani",role:"ASSOC.PROF.",dept:"CSE",campus:"KLV"},
  {name:"Dr. Batta Uma Maheswara Rao",role:"ASSOC.PROF.",dept:"CSE",campus:"KLV"},
  {name:"Dr. Vijaya Chandra Jadala",role:"ASSOC.PROF.",dept:"CSE",campus:"KLV"},
  {name:"Dr. Basaba Bikram Kumar",role:"ASSOC.PROF.",dept:"CSE",campus:"KLV"},
  {name:"Dr. Sathish Kumar Kannaiah",role:"ASSOC.PROF.",dept:"CSE",campus:"KLV"},
  {name:"Dr. Karyemsetty Nagarjuna",role:"ASSOC.PROF.",dept:"CSE",campus:"KLV"},
  {name:"Dr. Suneetha Bulla",role:"ASSOC.PROF.",dept:"CSE",campus:"KLV"},
  {name:"Dr. Raja Govindan",role:"ASSOC.PROF.",dept:"CSE",campus:"KLV"},
  {name:"Dr. S Srithar",role:"ASSOC.PROF.",dept:"CSE",campus:"KLV"},
  {name:"Dr. Akhilesh Kumar Dubey",role:"ASSOC.PROF.",dept:"CSE",campus:"KLV"},
  {name:"Dr. Thati Anuradha",role:"ASSOC.PROF.",dept:"CSE",campus:"KLV"},
  {name:"Dr. Kailasam Swathi",role:"ASSOC.PROF.",dept:"CSE",campus:"KLV"},
  {name:"Dr. Prashant Kumar Shukla",role:"ASSOC.PROF.",dept:"CSE",campus:"KLV"},
  {name:"Dr. Basant Sah",role:"ASSOC.PROF.",dept:"CSE",campus:"KLV"},
  {name:"Dr. M M Yamuna Devi",role:"ASSOC.PROF.",dept:"CSE",campus:"KLV"},
  {name:"Dr. Iwin Thanakumar Joseph S",role:"ASSOC.PROF.",dept:"CSE",campus:"KLV"},
  {name:"Dr. Nesarani A",role:"ASSOC.PROF.",dept:"CSE",campus:"KLV"},
  {name:"Dr. A Raja Basha",role:"ASSOC.PROF.",dept:"CSE",campus:"KLV"},
  {name:"Dr. Garikapati Bindu",role:"ASSOC.PROF.",dept:"CSE",campus:"KLV"},
  {name:"Dr. Tammineedi Venkata Satya Vivek",role:"ASSOC.PROF.",dept:"CSE",campus:"KLV"},
  {name:"Dr. Vignesh Thangathurai",role:"ASSOC.PROF.",dept:"CSE",campus:"KLV"},
  {name:"Dr. Mohammad Ishrat",role:"ASSOC.PROF.",dept:"CSE",campus:"KLV"},
  {name:"Dr. Jalaluddin Khan",role:"ASSOC.PROF.",dept:"CSE",campus:"KLV"},
  {name:"Dr. A R Deepa",role:"ASSOC.PROF.",dept:"CSE",campus:"KLV"},
  {name:"Dr. Maydiga Madhusudana Subramanyam",role:"ASSOC.PROF.",dept:"CSE",campus:"KLV"},
  {name:"Dr. Vijaya Kumar Reddy Radha",role:"ASSOC.PROF.",dept:"CSE",campus:"KLV"},
  {name:"Dr. Sanjay Yadav",role:"ASSOC.PROF.",dept:"CSE",campus:"KLV"},
  {name:"Dr. Veeraswamy Ammisetty",role:"ASSOC.PROF.",dept:"CSE",campus:"KLV"},
  {name:"Dr. Rafeeq Ahmed",role:"ASSOC.PROF.",dept:"CSE",campus:"KLV"},
  {name:"Dr. Jagadish Gurrala",role:"ASSOC.PROF.",dept:"CSE",campus:"KLV"},
  {name:"Dr. Kapil Agarwal",role:"ASSOC.PROF.",dept:"CSE",campus:"KLV"},
  {name:"Dr. Chippada Nagamani",role:"ASSOC.PROF.",dept:"CSE",campus:"KLV"},
  {name:"Dr. Vuda Sreenivasa Rao",role:"ASSOC.PROF.",dept:"CSE",campus:"KLV"},
  {name:"Dr. Vemula Venkata Jaya Rama Krishnaiah",role:"ASSOC.PROF.",dept:"CSE",campus:"KLV"},
  {name:"Dr. Sasanko Sekhar Gantayat",role:"ASSOC.PROF.",dept:"CSE",campus:"KLV"},
  {name:"Dr. Sunitha E V",role:"ASSOC.PROF.",dept:"CSE",campus:"KLV"},
  {name:"Dr. Gaddam Venu Gopal",role:"ASSOC.PROF.",dept:"CSE",campus:"KLV"},
  {name:"Dr. Anantharaman R",role:"ASSOC.PROF.",dept:"CSE",campus:"KLV"},
  {name:"Dr. Jayavarapu Karthik",role:"ASSOC.PROF.",dept:"CSE",campus:"KLV"},
  {name:"Dr. Shaik Khaja Mohiddin",role:"ASSOC.PROF.",dept:"CSE",campus:"KLV"},
  {name:"Dr. G V Sam Kumar",role:"ASSOC.PROF.",dept:"CSE",campus:"KLV"},
  {name:"Dr. Satrughan Kumar",role:"ASSOC.PROF.",dept:"CSE",campus:"KLV"},
  {name:"Dr. Surya Kiran Chebrolu",role:"ASSOC.PROF.",dept:"CSE",campus:"KLV"},
  {name:"Dr. B Annapurnna",role:"ASSOC.PROF.",dept:"CSE",campus:"KLV"},
  {name:"Dr. Bhabendu Kumar Mohanta",role:"ASSOC.PROF.",dept:"CSE",campus:"KLV"},
  {name:"Dr. S Aravinth Seshadri",role:"ASSOC.PROF.",dept:"CSE",campus:"KLV"},
  {name:"Dr. Ashok Kumar",role:"ASSOC.PROF.",dept:"CSE",campus:"KLV"},
  {name:"Dr. Jogendra Kumar",role:"ASSOC.PROF.",dept:"CSE",campus:"KLV"},
  {name:"Dr. SK Razia",role:"ASSOC.PROF.",dept:"CSE",campus:"KLV"},
  {name:"Dr. Sridevi Emandi",role:"ASSOC.PROF.",dept:"CSE",campus:"KLV"},
  {name:"Dr. N V S Pavan Kumar",role:"ASSOC.PROF.",dept:"CSE",campus:"KLV"},
  {name:"Dr. Pathuri Siva Kumar",role:"ASSOC.PROF.",dept:"CSE",campus:"KLV"},
  {name:"Dr. Marouthu Anusha",role:"ASSOC.PROF.",dept:"CSE",campus:"KLV"},
  {name:"Dr. Ashish",role:"ASSOC.PROF.",dept:"CSE",campus:"KLV"},
  {name:"Dr. Deepak Kumar Panda",role:"ASSOC.PROF.",dept:"CSE",campus:"KLV"},
  {name:"Dr. Gandla Shivakanth",role:"ASSOC.PROF.",dept:"CSE",campus:"KLV"},
  {name:"Dr. Meganathan Ramasamy",role:"ASSOC.PROF.",dept:"CSE",campus:"KLV"},
  {name:"Dr. Donti Reddy Usha Rani",role:"ASSOC.PROF.",dept:"CSE",campus:"KLV"},
  {name:"Ms. M V B T Santhi",role:"ASSOC.PROF.",dept:"CSE",campus:"KLV"},
  {name:"Mr. Anumalasetty Satya Kalyan",role:"ASSOC.PROF.",dept:"CSE",campus:"KLV"},
  {name:"Mr. Palacharla Srivenkata Srinivasa Sridhar",role:"ASSOC.PROF.",dept:"CSE",campus:"KLV"},
  {name:"Mr. Nimmagadda Sreeram",role:"ASSOC.PROF.",dept:"CSE",campus:"KLV"},
  {name:"Mr. M Vishnuvardhan",role:"ASSOC.PROF.",dept:"CSE",campus:"KLV"},
  {name:"Dr. Adapa Gopi",role:"ASSOC.PROF.",dept:"CSE",campus:"KLV"},
  {name:"Dr. Bechoo Lal",role:"ASSOC.PROF.",dept:"CSE",campus:"KLV"},
  {name:"Dr. Sanda Sri Harsha",role:"ASSOC.PROF.",dept:"CSE",campus:"KLV"},
  {name:"Dr. Jyothi N M",role:"ASSOC.PROF.",dept:"CSE",campus:"KLV"},
  {name:"Dr. Marapelli Bhaskar",role:"ASSOC.PROF.",dept:"CSE",campus:"KLV"},
  {name:"Dr. Durga Prasad Tripathi",role:"ASSOC.PROF.",dept:"CSE",campus:"KLV"},
  {name:"Dr. V Daya Sagar Ketaraju",role:"ASSOC.PROF.",dept:"CSE",campus:"KLV"},
  {name:"Dr. Kotagiri Vishnu Divya",role:"ASSOC.PROF.",dept:"CSE",campus:"KLV"},
  {name:"Dr. Sivapurapu Lavanya",role:"ASSOC.PROF.",dept:"CSE",campus:"KLV"},
  {name:"Dr. M Raja Ambethkar",role:"ASSOC.PROF.",dept:"CSE",campus:"KLV"},
  {name:"Dr. Kondapally Krishna Sunalini",role:"ASSOC.PROF.",dept:"CSE",campus:"KLV"},
  {name:"Dr. Mutyala Suresh",role:"ASSOC.PROF.",dept:"CSE",campus:"KLV"},
  {name:"Dr. Shaida Farhad",role:"ASSOC.PROF.",dept:"CSE",campus:"KLV"},
  {name:"Dr. Arnab Chatterjee",role:"ASSOC.PROF.",dept:"CSE",campus:"KLV"},
  {name:"Dr. K Madhu Murthy",role:"ASSOC.PROF.",dept:"CSE",campus:"KLV"},
  {name:"Dr. Thatavarthi Satish",role:"ASSOC.PROF.",dept:"CSE",campus:"KLV"},
  {name:"Dr. Riaz Shaik",role:"ASSOC.PROF.",dept:"CSE",campus:"KLV"},
  {name:"Dr. K V Chandra Sekhar",role:"ASSOC.PROF.",dept:"CSE",campus:"KLV"},
  {name:"Dr. B Srinivasa Kumar",role:"ASSOC.PROF.",dept:"CSE",campus:"KLV"},
  {name:"Dr. Grande Suresh Kumar",role:"ASSOC.PROF.",dept:"CSE",campus:"KLV"},
  {name:"Dr. D Sateesh Kumar",role:"ASSOC.PROF.",dept:"CSE",campus:"KLV"},
  {name:"Dr. Tamma Eswarlal",role:"ASSOC.PROF.",dept:"CSE",campus:"KLV"},
  {name:"Dr. Wuriti Sridhar",role:"ASSOC.PROF.",dept:"CSE",campus:"KLV"},
  {name:"Dr. T Nageswara Rao",role:"ASSOC.PROF.",dept:"CSE",campus:"KLV"},
  {name:"Dr. V B V N Prasad",role:"ASSOC.PROF.",dept:"CSE",campus:"KLV"},
  {name:"Dr. Nalleboyina Vijaya",role:"ASSOC.PROF.",dept:"CSE",campus:"KLV"},
  {name:"Dr. S Mohammed Ibrahim",role:"ASSOC.PROF.",dept:"CSE",campus:"KLV"},
  {name:"Dr. S Venumadhava Sarma",role:"ASSOC.PROF.",dept:"CSE",campus:"KLV"},
  {name:"Dr. M Nageswara Rao",role:"ASSOC.PROF.",dept:"CSE",campus:"KLV"},
  {name:"Dr. Atul Bhattad",role:"ASSOC.PROF.",dept:"CSE",campus:"KLV"},
  {name:"Dr. Koneru Swapna",role:"ASSOC.PROF.",dept:"CSE",campus:"KLV"},
  {name:"Dr. N S M P Latha Devi",role:"ASSOC.PROF.",dept:"CSE",campus:"KLV"},
  {name:"Dr. Shaik Mahamuda",role:"ASSOC.PROF.",dept:"CSE",campus:"KLV"},
  {name:"Dr. Kanike Raghavendra Kumar",role:"ASSOC.PROF.",dept:"CSE",campus:"KLV"},
  // CSE KLV Asst Profs - keeping representative set
  {name:"Dr. N B Arune Kumar",role:"ASST.PROF.",dept:"CSE",campus:"KLV"},
  {name:"Dr. Dyuti Banerjee",role:"ASST.PROF.",dept:"CSE",campus:"KLV"},
  {name:"Ms. Mandapati Praveena",role:"ASST.PROF.",dept:"CSE",campus:"KLV"},
  {name:"Mr. Nichenametla Rajesh",role:"ASST.PROF.",dept:"CSE",campus:"KLV"},
  {name:"Dr. Siva Sankar Mandal Baidya",role:"ASST.PROF.",dept:"CSE",campus:"KLV"},
  {name:"Dr. Pavan Kumar Bada",role:"ASST.PROF.",dept:"CSE",campus:"KLV"},
  {name:"Dr. Naresh Mameda",role:"ASST.PROF.",dept:"CSE",campus:"KLV"},
  {name:"Dr. Koyilapu Rambabu",role:"ASST.PROF.",dept:"CSE",campus:"KLV"},
  {name:"Dr. Gaddameedi Dinesh Kumar",role:"ASST.PROF.",dept:"CSE",campus:"KLV"},
  {name:"Dr. Mylavarapu Sita Ram Prasad",role:"ASST.PROF.",dept:"CSE",campus:"KLV"},
  {name:"Dr. Jampani Satish Babu",role:"ASST.PROF.",dept:"CSE",campus:"KLV"},
  {name:"Dr. Chitta M H Sai Baba",role:"ASST.PROF.",dept:"CSE",campus:"KLV"},
  {name:"Dr. Kottapalli Rajya Lakshmi",role:"ASST.PROF.",dept:"CSE",campus:"KLV"},
  {name:"Dr. Dasari Ramesh",role:"ASST.PROF.",dept:"CSE",campus:"KLV"},
  {name:"Dr. Beluguru Venkateswarulu",role:"ASST.PROF.",dept:"CSE",campus:"KLV"},
  {name:"Dr. Maganti Syamala",role:"ASST.PROF.",dept:"CSE",campus:"KLV"},
  {name:"Dr. Bakka Vinod",role:"ASST.PROF.",dept:"CSE",campus:"KLV"},
  {name:"Dr. Imran Rasheed",role:"ASST.PROF.",dept:"CSE",campus:"KLV"},
  {name:"Dr. Devendra Joshi",role:"ASST.PROF.",dept:"CSE",campus:"KLV"},
  {name:"Dr. Asesh Kumar Tripathy",role:"ASST.PROF.",dept:"CSE",campus:"KLV"},
  {name:"Dr. Veera Ankalu Vuyyuru",role:"ASST.PROF.",dept:"CSE",campus:"KLV"},
  {name:"Dr. Renuka Kolandasamy",role:"ASST.PROF.",dept:"CSE",campus:"KLV"},
  {name:"Dr. Abhishek Guru",role:"ASST.PROF.",dept:"CSE",campus:"KLV"},
  {name:"Dr. Sajja Tulasi Krishna",role:"ASST.PROF.",dept:"CSE",campus:"KLV"},
  {name:"Dr. Elima Hussain",role:"ASST.PROF.",dept:"CSE",campus:"KLV"},
  {name:"Dr. Koppuravuri Gurnadha Gupta",role:"ASST.PROF.",dept:"CSE",campus:"KLV"},
  {name:"Dr. G Kadiravan",role:"ASST.PROF.",dept:"CSE",campus:"KLV"},
  {name:"Dr. Wasim Khan",role:"ASST.PROF.",dept:"CSE",campus:"KLV"},
  {name:"Dr. R Mahendran",role:"ASST.PROF.",dept:"CSE",campus:"KLV"},
  {name:"Dr. Rahul Kumar",role:"ASST.PROF.",dept:"CSE",campus:"KLV"},
  {name:"Dr. Peruri Venkata Anusha",role:"ASST.PROF.",dept:"CSE",campus:"KLV"},
  {name:"Dr. Kodali Sadhana",role:"ASST.PROF.",dept:"CSE",campus:"KLV"},
  {name:"Dr. K Venkateswara Rao",role:"ASST.PROF.",dept:"CSE",campus:"KLV"},
  {name:"Dr. S Phani Kumar",role:"ASST.PROF.",dept:"CSE",campus:"KLV"},
  {name:"Dr. Bhimavarapu Usha Rani",role:"ASST.PROF.",dept:"CSE",campus:"KLV"},
  {name:"Dr. Karri Aruna Bhaskar",role:"ASST.PROF.",dept:"CSE",campus:"KLV"},
  {name:"Dr. M Supriya Menon",role:"ASST.PROF.",dept:"CSE",campus:"KLV"},
  {name:"Dr. Anitha Pradhan",role:"ASST.PROF.",dept:"CSE",campus:"KLV"},
  {name:"Dr. Abdul Hannan",role:"ASST.PROF.",dept:"CSE",campus:"KLV"},
  {name:"Dr. B Hanumantha Rao",role:"ASST.PROF.",dept:"CSE",campus:"KLV"},
  {name:"Dr. Macherla Padmavathi",role:"ASST.PROF.",dept:"CSE",campus:"KLV"},
  {name:"Dr. Anwar Ahmad Shaik",role:"ASST.PROF.",dept:"CSE",campus:"KLV"},
  {name:"Mr. Dama Anand",role:"ASST.PROF.",dept:"CSE",campus:"KLV"},
  {name:"Mr. Lakshminarayana Kodavali",role:"ASST.PROF.",dept:"CSE",campus:"KLV"},
  {name:"Ms. Kolachana Swetha",role:"ASST.PROF.",dept:"CSE",campus:"KLV"},
  {name:"Mr. Talasila Vamsidhar",role:"ASST.PROF.",dept:"CSE",campus:"KLV"},
  {name:"Mr. Vijay Kumar Vasantham",role:"ASST.PROF.",dept:"CSE",campus:"KLV"},
  {name:"Mr. Ramaiah Challa",role:"ASST.PROF.",dept:"CSE",campus:"KLV"},
  {name:"Ms. Bhavani Vasantha",role:"ASST.PROF.",dept:"CSE",campus:"KLV"},
  {name:"Ms. Valasapalli Mounika",role:"ASST.PROF.",dept:"CSE",campus:"KLV"},
  {name:"Mr. Janjhyam Venkata Naga Ramesh",role:"ASST.PROF.",dept:"CSE",campus:"KLV"},
  {name:"Mr. Tirandasu Ravi Kumar",role:"ASST.PROF.",dept:"CSE",campus:"KLV"},
  {name:"Mr. Ande Pavan Kumar",role:"ASST.PROF.",dept:"CSE",campus:"KLV"},
  {name:"Ms. Puppala Ramya",role:"ASST.PROF.",dept:"CSE",campus:"KLV"},
  {name:"Mr. Savaram Mythreya",role:"ASST.PROF.",dept:"CSE",campus:"KLV"},
  {name:"Mr. Garigipati Rama Krishna",role:"ASST.PROF.",dept:"CSE",campus:"KLV"},
  {name:"Mr. Doddi Suresh Kumar",role:"ASST.PROF.",dept:"CSE",campus:"KLV"},
  {name:"Ms. Garikipati Naga Lakshmi Sowjanya",role:"ASST.PROF.",dept:"CSE",campus:"KLV"},
  {name:"Mr. Arepalli Gopi",role:"ASST.PROF.",dept:"CSE",campus:"KLV"},
  {name:"Ms. Ponnuru Anusha",role:"ASST.PROF.",dept:"CSE",campus:"KLV"},
  {name:"Ms. Anjana Devi Akurathi",role:"ASST.PROF.",dept:"CSE",campus:"KLV"},
  {name:"Ms. Chinnam Sabitha",role:"ASST.PROF.",dept:"CSE",campus:"KLV"},
  {name:"Mr. Chittibabu Ravela",role:"ASST.PROF.",dept:"CSE",campus:"KLV"},
  {name:"Mr. Rupani Ranjith Kumar",role:"ASST.PROF.",dept:"CSE",campus:"KLV"},
  {name:"Ms. Bommisetti Yamini Supriya",role:"ASST.PROF.",dept:"CSE",campus:"KLV"},
  {name:"Ms. Pacha Supriya",role:"ASST.PROF.",dept:"CSE",campus:"KLV"},
  {name:"Mr. B Namasivayam",role:"ASST.PROF.",dept:"CSE",campus:"KLV"},
  {name:"Ms. Bandeela Suneetha",role:"ASST.PROF.",dept:"CSE",campus:"KLV"},
  {name:"Mr. Vuyyuru Lakshma Reddy",role:"ASST.PROF.",dept:"CSE",campus:"KLV"},
  {name:"Mr. Rajesh Tulasi",role:"ASST.PROF.",dept:"CSE",campus:"KLV"},
  {name:"Ms. Mandava Manjusha",role:"ASST.PROF.",dept:"CSE",campus:"KLV"},
  {name:"Ms. Chopparapu Gowthami",role:"ASST.PROF.",dept:"CSE",campus:"KLV"},
  {name:"Ms. Dasari Manasa",role:"ASST.PROF.",dept:"CSE",campus:"KLV"},
  {name:"Ms. Linginedi Usha Sree",role:"ASST.PROF.",dept:"CSE",campus:"KLV"},
  {name:"Mr. Kasturi Sai Sandeep",role:"ASST.PROF.",dept:"CSE",campus:"KLV"},
  {name:"Mr. Dhanesh Kumar",role:"ASST.PROF.",dept:"CSE",campus:"KLV"},
  {name:"Mr. Paladugu Venkateswara Rao",role:"ASST.PROF.",dept:"CSE",campus:"KLV"},
  {name:"Ms. Prasanthi Valluri",role:"ASST.PROF.",dept:"CSE",campus:"KLV"},
  {name:"Ms. Vuyyuru Lalitha",role:"ASST.PROF.",dept:"CSE",campus:"KLV"},
  {name:"Ms. Kowtharapu Radha",role:"ASST.PROF.",dept:"CSE",campus:"KLV"},
  {name:"Ms. Gorrepati Rajani Reddy",role:"ASST.PROF.",dept:"CSE",campus:"KLV"},
  {name:"Mr. Mylapalli Ramesh",role:"ASST.PROF.",dept:"CSE",campus:"KLV"},
  {name:"Dr. Swarna Anjali Devi",role:"ASST.PROF.",dept:"CSE",campus:"KLV"},
  {name:"Dr. P V V S Srinivas",role:"ASST.PROF.",dept:"CSE",campus:"KLV"},
  {name:"Dr. Dukkipati Sudha",role:"ASST.PROF.",dept:"CSE",campus:"KLV"},
  {name:"Dr. Avula Pavani",role:"ASST.PROF.",dept:"CSE",campus:"KLV"},
  {name:"Dr. Kammari Usha Rani",role:"ASST.PROF.",dept:"CSE",campus:"KLV"},
  {name:"Dr. Amara Rama Devi",role:"ASST.PROF.",dept:"CSE",campus:"KLV"},
  {name:"Dr. Twinkle Dasari",role:"ASST.PROF.",dept:"CSE",campus:"KLV"},
  {name:"Dr. Bathina Rajesh Kumar",role:"ASST.PROF.",dept:"CSE",campus:"KLV"},
  {name:"Dr. Bansode Ganpat Sadhu",role:"ASST.PROF.",dept:"CSE",campus:"KLV"},
  {name:"Dr. Annam Venkata Padmavathi",role:"ASST.PROF.",dept:"CSE",campus:"KLV"},
  {name:"Dr. G Charan Kumar",role:"ASST.PROF.",dept:"CSE",campus:"KLV"},
  {name:"Dr. S Ragamayi",role:"ASST.PROF.",dept:"CSE",campus:"KLV"},
  {name:"Dr. Yella Bhargavi",role:"ASST.PROF.",dept:"CSE",campus:"KLV"},
  {name:"Dr. Pathuri Bindu",role:"ASST.PROF.",dept:"CSE",campus:"KLV"},
  {name:"Dr. Ankita Tiwari",role:"ASST.PROF.",dept:"CSE",campus:"KLV"},
  {name:"Dr. Karthik Chinnasamy",role:"ASST.PROF.",dept:"CSE",campus:"KLV"},
  {name:"Dr. Rojalini Patro",role:"ASST.PROF.",dept:"CSE",campus:"KLV"},
  {name:"Dr. Ramesh Babu Nedumaran",role:"ASST.PROF.",dept:"CSE",campus:"KLV"},
  {name:"Dr. Imran Ali",role:"ASST.PROF.",dept:"CSE",campus:"KLV"},
  {name:"Dr. Ch Vasavi",role:"ASST.PROF.",dept:"CSE",campus:"KLV"},
  {name:"Dr. Tellakula Anitha",role:"ASST.PROF.",dept:"CSE",campus:"KLV"},
  {name:"Dr. B Giri Murugan",role:"ASST.PROF.",dept:"CSE",campus:"KLV"},
  {name:"Dr. Irrinki Mohan Krishna",role:"ASST.PROF.",dept:"CSE",campus:"KLV"},
  {name:"Dr. Konka Soujanya",role:"ASST.PROF.",dept:"CSE",campus:"KLV"},
  {name:"Dr. Ratna Valli Bhagavatula",role:"ASST.PROF.",dept:"CSE",campus:"KLV"},
  {name:"Dr. Venkata Naga Siva Kumar Challa",role:"ASST.PROF.",dept:"CSE",campus:"KLV"},
  {name:"Dr. Munish Kumar",role:"ASST.PROF.",dept:"CSE",campus:"KLV"},
  {name:"Dr. Sonali Biswas",role:"ASST.PROF.",dept:"CSE",campus:"KLV"},
  // EEE KLV
  {name:"Dr. Kotamaraju Subba Rao",role:"PROFESSOR",dept:"EEE",campus:"KLV"},
  {name:"Dr. A Pandian",role:"PROFESSOR",dept:"EEE",campus:"KLV"},
  {name:"Dr. Jarupula Somlal",role:"PROFESSOR",dept:"EEE",campus:"KLV"},
  {name:"Dr. S V N L Lalitha",role:"PROFESSOR",dept:"EEE",campus:"KLV"},
  {name:"Dr. Burthi Loveswara Rao",role:"PROFESSOR",dept:"EEE",campus:"KLV"},
  {name:"Dr. Kuthuri Narasimha Raju",role:"PROFESSOR",dept:"EEE",campus:"KLV"},
  {name:"Dr. Batchalakuri Jyothi",role:"ASSOC.PROF.",dept:"EEE",campus:"KLV"},
  {name:"Dr. Pinni Srinivasa Varma",role:"ASSOC.PROF.",dept:"EEE",campus:"KLV"},
  {name:"Dr. Malligunta Kiran Kumar",role:"ASSOC.PROF.",dept:"EEE",campus:"KLV"},
  {name:"Dr. Goda Ganesh Raja Sekhar",role:"ASSOC.PROF.",dept:"EEE",campus:"KLV"},
  {name:"Ms. Kota Sarada",role:"ASSOC.PROF.",dept:"EEE",campus:"KLV"},
  {name:"Mr. Daka Seshi Reddy",role:"ASSOC.PROF.",dept:"EEE",campus:"KLV"},
  {name:"Mr. R Bhanu Raghava Prakash",role:"ASSOC.PROF.",dept:"EEE",campus:"KLV"},
  {name:"Dr. Tadanki Vijay Muni",role:"ASST.PROF.",dept:"EEE",campus:"KLV"},
  {name:"Mr. Tadivaka Teja Sreenu",role:"ASST.PROF.",dept:"EEE",campus:"KLV"},
  // ECE KLV
  {name:"Dr. Venkatram Nidumolu",role:"PROFESSOR",dept:"ECE",campus:"KLV"},
  {name:"Dr. A S Chandra Sekhara Sastry",role:"PROFESSOR",dept:"ECE",campus:"KLV"},
  {name:"Dr. Vullanki Rajesh",role:"PROFESSOR",dept:"ECE",campus:"KLV"},
  {name:"Dr. Suman Maloji",role:"PROFESSOR",dept:"ECE",campus:"KLV"},
  {name:"Dr. Habibulla Khan",role:"PROFESSOR",dept:"ECE",campus:"KLV"},
  {name:"Dr. Chinnari Sri Kavya Korada",role:"PROFESSOR",dept:"ECE",campus:"KLV"},
  {name:"Dr. Kotamaraju Sarat Kumar",role:"PROFESSOR",dept:"ECE",campus:"KLV"},
  {name:"Dr. B T P Madhav",role:"PROFESSOR",dept:"ECE",campus:"KLV"},
  {name:"Dr. Immadi Govardhini",role:"PROFESSOR",dept:"ECE",campus:"KLV"},
  {name:"Dr. M Siva Ganga Prasad",role:"PROFESSOR",dept:"ECE",campus:"KLV"},
  {name:"Dr. Madhavareddy Venkata Narayana",role:"PROFESSOR",dept:"ECE",campus:"KLV"},
  {name:"Dr. Kakarla Hari Kishore",role:"PROFESSOR",dept:"ECE",campus:"KLV"},
  {name:"Dr. Miryala Sridhar",role:"PROFESSOR",dept:"ECE",campus:"KLV"},
  {name:"Dr. Venkata Ratnam Devanaboyina",role:"PROFESSOR",dept:"ECE",campus:"KLV"},
  {name:"Dr. Ghali Venkata Subba Rao",role:"PROFESSOR",dept:"ECE",campus:"KLV"},
  {name:"Dr. Ketavath Kumar Naik",role:"PROFESSOR",dept:"ECE",campus:"KLV"},
  {name:"Dr. Mohammad Zia Ur Rahman",role:"PROFESSOR",dept:"ECE",campus:"KLV"},
  {name:"Dr. Polurie Venkata Vijay Kishore",role:"PROFESSOR",dept:"ECE",campus:"KLV"},
  {name:"Dr. Karumuri Srinivasa Rao",role:"PROFESSOR",dept:"ECE",campus:"KLV"},
  {name:"Dr. Sujatha Moorthy",role:"PROFESSOR",dept:"ECE",campus:"KLV"},
  {name:"Dr. Thirumuru Rama Krishna",role:"PROFESSOR",dept:"ECE",campus:"KLV"},
  {name:"Dr. Penke Satyannarayana",role:"PROFESSOR",dept:"ECE",campus:"KLV"},
  {name:"Dr. Komaragiri Raghava Rao",role:"PROFESSOR",dept:"ECE",campus:"KLV"},
  {name:"Dr. Pabbisetti Satya Gouri Arunasri",role:"PROFESSOR",dept:"ECE",campus:"KLV"},
  {name:"Dr. Ravi Kumar Mokkapati",role:"ASSOC.PROF.",dept:"ECE",campus:"KLV"},
  {name:"Dr. Kallakunta Ravi Kumar",role:"ASSOC.PROF.",dept:"ECE",campus:"KLV"},
  {name:"Dr. Gorla Venkata Ganesh",role:"ASSOC.PROF.",dept:"ECE",campus:"KLV"},
  {name:"Dr. Munuswamy Siva Kumar",role:"ASSOC.PROF.",dept:"ECE",campus:"KLV"},
  {name:"Dr. Syed Inthiyaz",role:"ASSOC.PROF.",dept:"ECE",campus:"KLV"},
  {name:"Dr. Fazal Noor Basha",role:"ASSOC.PROF.",dept:"ECE",campus:"KLV"},
  {name:"Dr. Syed Shameem",role:"ASSOC.PROF.",dept:"ECE",campus:"KLV"},
  {name:"Dr. Guda Rama Krishna Prasad",role:"ASSOC.PROF.",dept:"ECE",campus:"KLV"},
  {name:"Dr. Dokku Bhavana",role:"ASSOC.PROF.",dept:"ECE",campus:"KLV"},
  {name:"Dr. Sreevardhan Cheerla",role:"ASSOC.PROF.",dept:"ECE",campus:"KLV"},
  {name:"Dr. Badugu Suresh",role:"ASSOC.PROF.",dept:"ECE",campus:"KLV"},
  {name:"Dr. Chakka Raghava Prasad",role:"ASSOC.PROF.",dept:"ECE",campus:"KLV"},
  {name:"Dr. Pokkunuri Pardha Saradhi",role:"ASSOC.PROF.",dept:"ECE",campus:"KLV"},
  {name:"Dr. Devireddy Sreenivasa Rao",role:"ASSOC.PROF.",dept:"ECE",campus:"KLV"},
  {name:"Dr. Pathan Saleem Akram",role:"ASSOC.PROF.",dept:"ECE",campus:"KLV"},
  {name:"Dr. Gubbala China Satyanarayana",role:"ASSOC.PROF.",dept:"ECE",campus:"KLV"},
  {name:"Dr. Katta Rajesh Babu",role:"ASSOC.PROF.",dept:"ECE",campus:"KLV"},
  {name:"Dr. G Sai Krishna Santosh",role:"ASSOC.PROF.",dept:"ECE",campus:"KLV"},
  {name:"Dr. Sampad Kumar Panda",role:"ASSOC.PROF.",dept:"ECE",campus:"KLV"},
  {name:"Dr. Ernest Ravindran R S",role:"ASSOC.PROF.",dept:"ECE",campus:"KLV"},
  {name:"Dr. Yalavarthi Usha Devi",role:"ASSOC.PROF.",dept:"ECE",campus:"KLV"},
  {name:"Dr. Kondaveeti Girija Sravani",role:"ASSOC.PROF.",dept:"ECE",campus:"KLV"},
  {name:"Dr. Mannepalli Kasi Prasad",role:"ASSOC.PROF.",dept:"ECE",campus:"KLV"},
  {name:"Dr. N Prabakaran",role:"ASSOC.PROF.",dept:"ECE",campus:"KLV"},
  {name:"Dr. Vipul Agarwal",role:"ASSOC.PROF.",dept:"ECE",campus:"KLV"},
  {name:"Dr. C Sreenivas Preetham Reddy",role:"ASSOC.PROF.",dept:"ECE",campus:"KLV"},
  {name:"Dr. Bukya Balaji",role:"ASSOC.PROF.",dept:"ECE",campus:"KLV"},
  {name:"Dr. M Muzammil Parvez",role:"ASSOC.PROF.",dept:"ECE",campus:"KLV"},
  {name:"Dr. Pillalamarri Syam Sundar",role:"ASSOC.PROF.",dept:"ECE",campus:"KLV"},
  {name:"Dr. Aswin Kumer S V",role:"ASSOC.PROF.",dept:"ECE",campus:"KLV"},
  {name:"Dr. Rallabandi Revathi",role:"ASSOC.PROF.",dept:"ECE",campus:"KLV"},
  {name:"Dr. S Rooban",role:"ASSOC.PROF.",dept:"ECE",campus:"KLV"},
  {name:"Dr. Chella Santhosh",role:"ASSOC.PROF.",dept:"ECE",campus:"KLV"},
  {name:"Dr. S Arun Metha",role:"ASSOC.PROF.",dept:"ECE",campus:"KLV"},
  {name:"Dr. Eepuri Kiran Kumar",role:"ASSOC.PROF.",dept:"ECE",campus:"KLV"},
  {name:"Dr. Aravind Kilaru",role:"ASSOC.PROF.",dept:"ECE",campus:"KLV"},
  {name:"Dr. Nagangabam Phalguni Singh",role:"ASSOC.PROF.",dept:"ECE",campus:"KLV"},
  {name:"Dr. Aravindhan Alagarsamy",role:"ASSOC.PROF.",dept:"ECE",campus:"KLV"},
  {name:"Dr. Abhishek Pahuja",role:"ASSOC.PROF.",dept:"ECE",campus:"KLV"},
  {name:"Dr. Ashish Kumar",role:"ASSOC.PROF.",dept:"ECE",campus:"KLV"},
  {name:"Dr. Sumit Bhushan",role:"ASSOC.PROF.",dept:"ECE",campus:"KLV"},
  {name:"Dr. Vivekananthan Venkateswaran",role:"ASSOC.PROF.",dept:"ECE",campus:"KLV"},
  {name:"Dr. Mareedu Venkata Durga Prasad",role:"ASSOC.PROF.",dept:"ECE",campus:"KLV"},
  {name:"Dr. Vasipalli Subba Reddy",role:"ASSOC.PROF.",dept:"ECE",campus:"KLV"},
  {name:"Dr. Nalluri Siddaiah",role:"ASSOC.PROF.",dept:"ECE",campus:"KLV"},
  {name:"Dr. Midasala Vasuja Devi",role:"ASSOC.PROF.",dept:"ECE",campus:"KLV"},
  {name:"Dr. Sunil Kumar",role:"ASSOC.PROF.",dept:"ECE",campus:"KLV"},
  {name:"Dr. Nagesh Mantravadi",role:"ASSOC.PROF.",dept:"ECE",campus:"KLV"},
  {name:"Dr. Tatini Narendra Babu",role:"ASSOC.PROF.",dept:"ECE",campus:"KLV"},
  {name:"Dr. Kolluru Venkata Ratnam",role:"ASSOC.PROF.",dept:"ECE",campus:"KLV"},
  {name:"Dr. Jyothi Ravi Kiran Kumar Dabbakuti",role:"ASSOC.PROF.",dept:"ECE",campus:"KLV"},
  {name:"Dr. Poruri Gopi Krishna",role:"ASSOC.PROF.",dept:"ECE",campus:"KLV"},
  {name:"Dr. Karra Sony",role:"ASST.PROF.",dept:"ECE",campus:"KLV"},
  {name:"Dr. Kasi Uday Kiran",role:"ASST.PROF.",dept:"ECE",campus:"KLV"},
  {name:"Dr. Kambhampati Venkata Sowmya",role:"ASST.PROF.",dept:"ECE",campus:"KLV"},
  {name:"Dr. Somavarapu Vamsee Krishna",role:"ASST.PROF.",dept:"ECE",campus:"KLV"},
  {name:"Dr. Naren Das",role:"ASST.PROF.",dept:"ECE",campus:"KLV"},
  {name:"Dr. Atul Kumar",role:"ASST.PROF.",dept:"ECE",campus:"KLV"},
  {name:"Dr. Shaik Hasane Ahammad",role:"ASST.PROF.",dept:"ECE",campus:"KLV"},
  {name:"Dr. Abhishek Kumar",role:"ASST.PROF.",dept:"ECE",campus:"KLV"},
  {name:"Dr. Debajit Deb",role:"ASST.PROF.",dept:"ECE",campus:"KLV"},
  {name:"Dr. Vasimalla Yesu Dasu",role:"ASST.PROF.",dept:"ECE",campus:"KLV"},
  {name:"Dr. Lokendra Singh",role:"ASST.PROF.",dept:"ECE",campus:"KLV"},
  {name:"Dr. Chatragadda Gopi Chand",role:"ASST.PROF.",dept:"ECE",campus:"KLV"},
  {name:"Ms. Vankayalapati Sahiti",role:"ASST.PROF.",dept:"ECE",campus:"KLV"},
  {name:"Mr. Banda Sai Sandeep",role:"ASST.PROF.",dept:"ECE",campus:"KLV"},
  {name:"Dr. Jammalamadaka Rajasekhar",role:"ASST.PROF.",dept:"ECE",campus:"KLV"},
  // MATHEMATICS KLV
  {name:"Dr. B V Appa Rao",role:"PROFESSOR",dept:"Mathematics",campus:"KLV"},
  {name:"Dr. N Konda Reddy",role:"ASSOC.PROF.",dept:"Mathematics",campus:"KLV"},
  // MECHANICAL ENGINEERING KLV
  {name:"Dr. Konijeti Rama Krishna",role:"PROFESSOR",dept:"Mechanical Engineering",campus:"KLV"},
  {name:"Dr. Adusumilli Srinath",role:"PROFESSOR",dept:"Mechanical Engineering",campus:"KLV"},
  {name:"Dr. N B V Prasad",role:"PROFESSOR",dept:"Mechanical Engineering",campus:"KLV"},
  {name:"Dr. P Venkata Chalapathi",role:"PROFESSOR",dept:"Mechanical Engineering",campus:"KLV"},
  {name:"Dr. Seeram Srinivasa Rao",role:"PROFESSOR",dept:"Mechanical Engineering",campus:"KLV"},
  {name:"Dr. Surya Narayana Padhi",role:"PROFESSOR",dept:"Mechanical Engineering",campus:"KLV"},
  {name:"Dr. Garikapati Diwakar",role:"PROFESSOR",dept:"Mechanical Engineering",campus:"KLV"},
  {name:"Dr. Kurapati Venkata Narasimha Rao",role:"PROFESSOR",dept:"Mechanical Engineering",campus:"KLV"},
  {name:"Dr. G Murali",role:"PROFESSOR",dept:"Mechanical Engineering",campus:"KLV"},
  {name:"Dr. V L Mangesh",role:"PROFESSOR",dept:"Mechanical Engineering",campus:"KLV"},
  {name:"Dr. T Vijaya Kumar",role:"ASSOC.PROF.",dept:"Mechanical Engineering",campus:"KLV"},
  {name:"Dr. Devulapalli V A Rama Sastry",role:"ASSOC.PROF.",dept:"Mechanical Engineering",campus:"KLV"},
  {name:"Dr. G Yedukondalu",role:"ASSOC.PROF.",dept:"Mechanical Engineering",campus:"KLV"},
  {name:"Dr. Kanchu Venkata Durga Rajesh",role:"ASSOC.PROF.",dept:"Mechanical Engineering",campus:"KLV"},
  {name:"Dr. Pothamsetty Kasi Visweswara Rao",role:"ASSOC.PROF.",dept:"Mechanical Engineering",campus:"KLV"},
  {name:"Dr. Priyaranjan Sharma",role:"ASSOC.PROF.",dept:"Mechanical Engineering",campus:"KLV"},
  {name:"Dr. Raj Kumar Pittala",role:"ASST.PROF.",dept:"Mechanical Engineering",campus:"KLV"},
  {name:"Dr. Vinay Atgur",role:"ASST.PROF.",dept:"Mechanical Engineering",campus:"KLV"},
  {name:"Dr. Arigela Sri Harsha",role:"ASST.PROF.",dept:"Mechanical Engineering",campus:"KLV"},
  {name:"Dr. Priyaranjan Samal",role:"ASST.PROF.",dept:"Mechanical Engineering",campus:"KLV"},
  {name:"Dr. Giphin George",role:"ASST.PROF.",dept:"Mechanical Engineering",campus:"KLV"},
  {name:"Dr. Dasore Abhishek",role:"ASST.PROF.",dept:"Mechanical Engineering",campus:"KLV"},
  // PHARMACY KLV
  {name:"Dr. Buchinaidu Nalluri",role:"PROFESSOR",dept:"Pharmacy",campus:"KLV"},
  {name:"Dr. Guntupalli Chakravarthi",role:"PROFESSOR",dept:"Pharmacy",campus:"KLV"},
  {name:"Dr. Tangallamudi Srinivasa Rao",role:"ASSOC.PROF.",dept:"Pharmacy",campus:"KLV"},
  {name:"Dr. B Kishore Babu",role:"ASSOC.PROF.",dept:"Pharmacy",campus:"KLV"},
  {name:"Dr. Areti Anka Rao",role:"ASSOC.PROF.",dept:"Pharmacy",campus:"KLV"},
  {name:"Dr. P Rajeswari",role:"ASSOC.PROF.",dept:"Pharmacy",campus:"KLV"},
  {name:"Dr. Manikanta Swamy Murahari",role:"ASSOC.PROF.",dept:"Pharmacy",campus:"KLV"},
  {name:"Dr. Kasi Viswanadh Matte",role:"ASSOC.PROF.",dept:"Pharmacy",campus:"KLV"},
  {name:"Dr. Kolli Deepti",role:"ASST.PROF.",dept:"Pharmacy",campus:"KLV"},
  {name:"Dr. Alka Damodhar Kamble",role:"ASST.PROF.",dept:"Pharmacy",campus:"KLV"},
  {name:"Dr. Malothu Narender",role:"ASST.PROF.",dept:"Pharmacy",campus:"KLV"},
  {name:"Dr. J Risy Namratha",role:"ASST.PROF.",dept:"Pharmacy",campus:"KLV"},
  {name:"Dr. Naresh Dumala",role:"ASST.PROF.",dept:"Pharmacy",campus:"KLV"},
  {name:"Dr. Sivadasu Praveen",role:"ASST.PROF.",dept:"Pharmacy",campus:"KLV"},
  {name:"Dr. Mobeen Shaik",role:"ASST.PROF.",dept:"Pharmacy",campus:"KLV"},
  {name:"Mr. Amareswarapu Venkata Surendra",role:"ASST.PROF.",dept:"Pharmacy",campus:"KLV"},
  {name:"Mr. Kakarla Rama Krishna",role:"ASST.PROF.",dept:"Pharmacy",campus:"KLV"},
  {name:"Dr. Banoth Karan Kumar",role:"ASST.PROF.",dept:"Pharmacy",campus:"KLV"},
  {name:"Dr. Rayana Supriya",role:"ASST.PROF.",dept:"Pharmacy",campus:"KLV"},
  {name:"Dr. Katari Sukeerthi",role:"ASST.PROF.",dept:"Pharmacy",campus:"KLV"},
  // PHYSICS KLV
  {name:"Dr. G Sunita Sundari",role:"ASSOC.PROF.",dept:"Physics",campus:"KLV"},
  {name:"Dr. M Venkateswarlu",role:"ASST.PROF.",dept:"Physics",campus:"KLV"},
  // SCHOOL OF LAW KLV
  {name:"Dr. Choudaraju Neelima",role:"ASSOC.PROF.",dept:"School of Law",campus:"KLV"},
  {name:"Dr. Jayaprakash Jala",role:"ASSOC.PROF.",dept:"School of Law",campus:"KLV"},
  {name:"Dr. Konduru Indu Pavan Kumar",role:"ASSOC.PROF.",dept:"School of Law",campus:"KLV"},
  {name:"Dr. Petikam Sailaja",role:"ASSOC.PROF.",dept:"School of Law",campus:"KLV"},
  {name:"Dr. Kalavacharla Veera Venkata Raju",role:"ASSOC.PROF.",dept:"School of Law",campus:"KLV"},
  {name:"Ms. Gottumukkala Vijaya Sudha",role:"ASST.PROF.",dept:"School of Law",campus:"KLV"},
  {name:"Dr. G Vinodini Devi",role:"ASST.PROF.",dept:"School of Law",campus:"KLV"},
  {name:"Dr. Peluru Thaviti Raju",role:"ASST.PROF.",dept:"School of Law",campus:"KLV"},
  {name:"Dr. Ravipati Kumara Swamy",role:"ASST.PROF.",dept:"School of Law",campus:"KLV"},
  {name:"Dr. Narendra Ryali",role:"ASST.PROF.",dept:"School of Law",campus:"KLV"},
  {name:"Dr. Vahed Shakeel Ahammad",role:"ASST.PROF.",dept:"School of Law",campus:"KLV"},
  {name:"Dr. Shyamasundar Tripathy",role:"ASST.PROF.",dept:"School of Law",campus:"KLV"},
  {name:"Dr. Yarlagadda Venkata Ramana",role:"ASST.PROF.",dept:"School of Law",campus:"KLV"},
  // HYDERABAD CAMPUS
  {name:"Ms. Suhashini Dash",role:"ASST.PROF.",dept:"Arts",campus:"HYD"},
  {name:"Dr. Anupama Gadiraju",role:"PROFESSOR",dept:"Business School",campus:"HYD"},
  {name:"Mr. Venu Madhav Vedantam",role:"ASSOC.PROF.",dept:"Business School",campus:"HYD"},
  {name:"Dr. P Hima Jagathi",role:"ASSOC.PROF.",dept:"Business School",campus:"HYD"},
  {name:"Dr. Swarupa Pelleti",role:"ASSOC.PROF.",dept:"Business School",campus:"HYD"},
  {name:"Dr. Rakesh Kumar Patra",role:"ASSOC.PROF.",dept:"Business School",campus:"HYD"},
  {name:"Dr. K Subha Gora",role:"ASSOC.PROF.",dept:"Business School",campus:"HYD"},
  {name:"Dr. B Balanagalakshmi",role:"ASST.PROF.",dept:"Business School",campus:"HYD"},
  {name:"Dr. Akanksha Dubey",role:"ASST.PROF.",dept:"Business School",campus:"HYD"},
  {name:"Dr. K Narendra Kumar",role:"ASST.PROF.",dept:"Business School",campus:"HYD"},
  {name:"Dr. Mohan Venkatesh Palani",role:"ASST.PROF.",dept:"Business School",campus:"HYD"},
  {name:"Dr. Priyadarshi Ranjan",role:"ASST.PROF.",dept:"Business School",campus:"HYD"},
  {name:"Ms. Susmita Ekka",role:"ASST.PROF.",dept:"Business School",campus:"HYD"},
  {name:"Mr. Bivas Paul",role:"ASST.PROF.",dept:"Business School",campus:"HYD"},
  {name:"Ms. Bhimireddy Sri Lakshmi",role:"ASST.PROF.",dept:"Business School",campus:"HYD"},
  {name:"Ms. Lena Joseph K",role:"ASST.PROF.",dept:"Business School",campus:"HYD"},
  {name:"Dr. Savadam Balaji",role:"PROFESSOR",dept:"CSE",campus:"HYD"},
  {name:"Dr. P Lalitha Surya Kumari",role:"PROFESSOR",dept:"CSE",campus:"HYD"},
  {name:"Dr. Mugunthan S R",role:"PROFESSOR",dept:"CSE",campus:"HYD"},
  {name:"Dr. K Srinivas",role:"PROFESSOR",dept:"CSE",campus:"HYD"},
  {name:"Dr. A Mahesh Babu",role:"PROFESSOR",dept:"CSE",campus:"HYD"},
  {name:"Dr. D Srinivas Rao",role:"PROFESSOR",dept:"CSE",campus:"HYD"},
  {name:"Dr. B Lakshmana Swamy",role:"PROFESSOR",dept:"CSE",campus:"HYD"},
  {name:"Dr. Gandikota Ramu",role:"PROFESSOR",dept:"CSE",campus:"HYD"},
  {name:"Dr. Srilakshmi Uppalapati",role:"PROFESSOR",dept:"CSE",campus:"HYD"},
  {name:"Dr. Amarana Prabhakar Rao",role:"PROFESSOR",dept:"CSE",campus:"HYD"},
  {name:"Dr. Geeta Mulabagula",role:"ASSOC.PROF.",dept:"CSE",campus:"HYD"},
  {name:"Dr. Jaya Vani Majumdar",role:"ASSOC.PROF.",dept:"CSE",campus:"HYD"},
  {name:"Dr. Sreedhar Gundekari",role:"ASSOC.PROF.",dept:"CSE",campus:"HYD"},
  {name:"Dr. Tanmay Mondal",role:"ASSOC.PROF.",dept:"CSE",campus:"HYD"},
  {name:"Dr. G Rekha",role:"ASSOC.PROF.",dept:"CSE",campus:"HYD"},
  {name:"Dr. K Rama Subrahmanian",role:"ASSOC.PROF.",dept:"CSE",campus:"HYD"},
  {name:"Dr. Sandeep Reddy Chitreddy",role:"ASSOC.PROF.",dept:"CSE",campus:"HYD"},
  {name:"Dr. C H J Srinivasa Rao Pasupuleti",role:"ASSOC.PROF.",dept:"CSE",campus:"HYD"},
  {name:"Dr. Paidi Ganaga Mohan",role:"ASSOC.PROF.",dept:"CSE",campus:"HYD"},
  {name:"Dr. Sheikh Fahad Ahmad",role:"ASSOC.PROF.",dept:"CSE",campus:"HYD"},
  {name:"Dr. Figlu Mohanty",role:"ASSOC.PROF.",dept:"CSE",campus:"HYD"},
  {name:"Dr. Arpita Gupta",role:"ASSOC.PROF.",dept:"CSE",campus:"HYD"},
  {name:"Dr. G Anna Lakshmi",role:"ASSOC.PROF.",dept:"CSE",campus:"HYD"},
  {name:"Dr. M Saidi Reddy",role:"ASSOC.PROF.",dept:"CSE",campus:"HYD"},
  {name:"Dr. Miriyala Trinath Basu",role:"ASSOC.PROF.",dept:"CSE",campus:"HYD"},
  {name:"Dr. Gayatri",role:"ASSOC.PROF.",dept:"CSE",campus:"HYD"},
  {name:"Dr. M P Mallesh",role:"ASSOC.PROF.",dept:"CSE",campus:"HYD"},
  {name:"Dr. Pramoda Patro",role:"ASSOC.PROF.",dept:"CSE",campus:"HYD"},
  {name:"Dr. Sivaram Boppe",role:"ASSOC.PROF.",dept:"CSE",campus:"HYD"},
  {name:"Dr. Suresh Kumar Yanduri",role:"ASSOC.PROF.",dept:"CSE",campus:"HYD"},
  {name:"Dr. Haribabu Kommadi",role:"ASSOC.PROF.",dept:"CSE",campus:"HYD"},
  {name:"Dr. Moon Banerjee",role:"ASSOC.PROF.",dept:"CSE",campus:"HYD"},
  {name:"Mr. Sasidhar Kothuru",role:"ASSOC.PROF.",dept:"CSE",campus:"HYD"},
  {name:"Dr. Preeti Jha",role:"ASSOC.PROF.",dept:"CSE",campus:"HYD"},
  {name:"Dr. Mohan Varkolu",role:"ASST.PROF.",dept:"CSE",campus:"HYD"},
  {name:"Dr. Aashiq Banu",role:"ASST.PROF.",dept:"CSE",campus:"HYD"},
  {name:"Dr. Sharanya V",role:"ASST.PROF.",dept:"CSE",campus:"HYD"},
  {name:"Dr. Vishala Pannala",role:"ASST.PROF.",dept:"CSE",campus:"HYD"},
  {name:"Dr. Pandava Sudharshan Babu",role:"ASST.PROF.",dept:"CSE",campus:"HYD"},
  {name:"Dr. Giridhar Urkude",role:"ASST.PROF.",dept:"CSE",campus:"HYD"},
  {name:"Dr. Shadab Siddiqui",role:"ASST.PROF.",dept:"CSE",campus:"HYD"},
  {name:"Dr. Sumit Hazra",role:"ASST.PROF.",dept:"CSE",campus:"HYD"},
  {name:"Dr. Rajib Debnath",role:"ASST.PROF.",dept:"CSE",campus:"HYD"},
  {name:"Dr. Kakali Das",role:"ASST.PROF.",dept:"CSE",campus:"HYD"},
  {name:"Dr. Subhranginee Das",role:"ASST.PROF.",dept:"CSE",campus:"HYD"},
  {name:"Dr. Gadde Sai Sudha",role:"ASST.PROF.",dept:"CSE",campus:"HYD"},
  {name:"Dr. P Pavan Kumar",role:"ASST.PROF.",dept:"CSE",campus:"HYD"},
  {name:"Dr. G Madhukar Rao",role:"ASST.PROF.",dept:"CSE",campus:"HYD"},
  {name:"Dr. A Ranganath",role:"ASST.PROF.",dept:"CSE",campus:"HYD"},
  {name:"Dr. Anantha Babu S",role:"ASST.PROF.",dept:"CSE",campus:"HYD"},
  {name:"Dr. Chandrashekar Boddu",role:"ASST.PROF.",dept:"CSE",campus:"HYD"},
  {name:"Dr. Abhishek Tah",role:"ASST.PROF.",dept:"CSE",campus:"HYD"},
  {name:"Dr. Tanushree Sarkar",role:"ASST.PROF.",dept:"CSE",campus:"HYD"},
  {name:"Dr. Bhavani Sushma Garlapati",role:"ASST.PROF.",dept:"CSE",campus:"HYD"},
  {name:"Dr. Kranthi Priya Oruganti",role:"ASST.PROF.",dept:"CSE",campus:"HYD"},
  {name:"Dr. Indira Kothalanka",role:"ASST.PROF.",dept:"CSE",campus:"HYD"},
  {name:"Dr. Kavuluri Jagan Mohan Rao",role:"ASST.PROF.",dept:"CSE",campus:"HYD"},
  {name:"Dr. Kalyan Kumar Palaparthi",role:"ASST.PROF.",dept:"CSE",campus:"HYD"},
  {name:"Dr. Najnin Islam",role:"ASST.PROF.",dept:"CSE",campus:"HYD"},
  {name:"Dr. Thota Venkata Deepthi",role:"ASST.PROF.",dept:"CSE",campus:"HYD"},
  {name:"Dr. Ramesh Ade",role:"ASST.PROF.",dept:"CSE",campus:"HYD"},
  {name:"Dr. Charanadhar Nagavolu",role:"ASST.PROF.",dept:"CSE",campus:"HYD"},
  {name:"Ms. Jayasri R",role:"ASST.PROF.",dept:"CSE",campus:"HYD"},
  {name:"Ms. Dayanika Jarugumalla",role:"ASST.PROF.",dept:"CSE",campus:"HYD"},
  {name:"Mr. Vijay Kumar Damera",role:"ASST.PROF.",dept:"CSE",campus:"HYD"},
  {name:"Mr. Panduraju Pagidimalla",role:"ASST.PROF.",dept:"CSE",campus:"HYD"},
  {name:"Mr. Anantha Reddy Dasari",role:"ASST.PROF.",dept:"CSE",campus:"HYD"},
  {name:"Mr. Chanda Raj Kumar",role:"ASST.PROF.",dept:"CSE",campus:"HYD"},
  {name:"Ms. Nidhi Srivastava",role:"ASST.PROF.",dept:"CSE",campus:"HYD"},
  {name:"Ms. Sumalakshmi C H",role:"ASST.PROF.",dept:"CSE",campus:"HYD"},
  {name:"Ms. Deepthi Kalavala",role:"ASST.PROF.",dept:"CSE",campus:"HYD"},
  {name:"Ms. N Anuradha",role:"ASST.PROF.",dept:"CSE",campus:"HYD"},
  {name:"Mr. D Vinod Kumar",role:"ASST.PROF.",dept:"CSE",campus:"HYD"},
  {name:"Ms. P Sree Lakshmi",role:"ASST.PROF.",dept:"CSE",campus:"HYD"},
  {name:"Mr. Faizan Ahmad",role:"ASST.PROF.",dept:"CSE",campus:"HYD"},
  {name:"Mr. Aftab Yaseen",role:"ASST.PROF.",dept:"CSE",campus:"HYD"},
  {name:"Mr. P Ratna Kumar",role:"ASST.PROF.",dept:"CSE",campus:"HYD"},
  {name:"Ms. Uma Rani Bodakunta",role:"ASST.PROF.",dept:"CSE",campus:"HYD"},
  {name:"Mr. Chiranjeevi N",role:"ASST.PROF.",dept:"CSE",campus:"HYD"},
  {name:"Ms. M Saritha",role:"ASST.PROF.",dept:"CSE",campus:"HYD"},
  {name:"Mr. Mainak Saha",role:"ASST.PROF.",dept:"CSE",campus:"HYD"},
  {name:"Mr. K Suresh",role:"ASST.PROF.",dept:"CSE",campus:"HYD"},
  {name:"Ms. Varala Venkata Naga Aruna Bhargavi",role:"ASST.PROF.",dept:"CSE",campus:"HYD"},
  {name:"Mr. D Srinivasa Rao",role:"ASST.PROF.",dept:"CSE",campus:"HYD"},
  {name:"Mrs. K Madhavi",role:"ASST.PROF.",dept:"CSE",campus:"HYD"},
  {name:"Dr. Mudhulkar Raju",role:"ASST.PROF.",dept:"CSE",campus:"HYD"},
  {name:"Dr. Mandapati Sridevi",role:"ASST.PROF.",dept:"CSE",campus:"HYD"},
  {name:"Mr. Gunturi S Raghavendra",role:"ASST.PROF.",dept:"CSE",campus:"HYD"},
  {name:"Dr. Mahadeva Swamy N N",role:"ASST.PROF.",dept:"CSE",campus:"HYD"},
  {name:"Ms. A Jayanthi",role:"ASST.PROF.",dept:"CSE",campus:"HYD"},
  {name:"Mrs. Neerati Lavanya",role:"ASST.PROF.",dept:"CSE",campus:"HYD"},
  {name:"Mr. Baddepaka Prasad",role:"ASST.PROF.",dept:"CSE",campus:"HYD"},
  {name:"Ms. K V Sharada",role:"ASST.PROF.",dept:"CSE",campus:"HYD"},
  {name:"Mr. K Rakesh",role:"ASST.PROF.",dept:"CSE",campus:"HYD"},
  {name:"Ms. G Mamatha",role:"ASST.PROF.",dept:"CSE",campus:"HYD"},
  {name:"Ms. P Swetha Nagasri",role:"ASST.PROF.",dept:"CSE",campus:"HYD"},
  {name:"Mr. Cherukupally Ram Anirudh",role:"ASST.PROF.",dept:"CSE",campus:"HYD"},
  {name:"Dr. M Goutham",role:"PROFESSOR",dept:"ECE",campus:"HYD"},
  {name:"Dr. A Rama Krishna",role:"ASSOC.PROF.",dept:"ECE",campus:"HYD"},
  {name:"Dr. Joshitha Chandrappan",role:"ASSOC.PROF.",dept:"ECE",campus:"HYD"},
  {name:"Dr. K V Prashanth",role:"ASSOC.PROF.",dept:"ECE",campus:"HYD"},
  {name:"Dr. Boda Ravi",role:"ASSOC.PROF.",dept:"ECE",campus:"HYD"},
  {name:"Dr. S Sanjay",role:"ASSOC.PROF.",dept:"ECE",campus:"HYD"},
  {name:"Dr. P Sudharsana Rao",role:"ASSOC.PROF.",dept:"ECE",campus:"HYD"},
  {name:"Dr. Abhishek Kumar Shrivastava",role:"ASSOC.PROF.",dept:"ECE",campus:"HYD"},
  {name:"Dr. B Anil Kumar",role:"ASSOC.PROF.",dept:"ECE",campus:"HYD"},
  {name:"Dr. Koteswara Rao L",role:"PROFESSOR",dept:"ECE",campus:"HYD"},
  {name:"Dr. Vijay Rao Kumbhare",role:"ASST.PROF.",dept:"ECE",campus:"HYD"},
  {name:"Dr. Sravan Kumar Gunturi",role:"ASST.PROF.",dept:"ECE",campus:"HYD"},
  {name:"Dr. Ashwini Kumar Varma",role:"ASST.PROF.",dept:"ECE",campus:"HYD"},
  {name:"Dr. Thirupathaiah Kola",role:"ASST.PROF.",dept:"ECE",campus:"HYD"},
  {name:"Dr. Bittu Kumar",role:"ASST.PROF.",dept:"ECE",campus:"HYD"},
  {name:"Ms. Prasanna Lakshmi Akella",role:"ASST.PROF.",dept:"ECE",campus:"HYD"},
  {name:"Mr. Sathish Ande",role:"ASST.PROF.",dept:"ECE",campus:"HYD"},
  {name:"Dr. Anga Srinivas",role:"ASST.PROF.",dept:"ECE",campus:"HYD"},
  {name:"Dr. M Seshadri",role:"ASST.PROF.",dept:"ECE",campus:"HYD"},
  {name:"Dr. G Durga Prasad",role:"ASST.PROF.",dept:"ECE",campus:"HYD"},
  {name:"Dr. Seethi Reddy Reddisekhar Reddy",role:"ASST.PROF.",dept:"ECE",campus:"HYD"},
  {name:"Dr. T Siva",role:"ASST.PROF.",dept:"ECE",campus:"HYD"},
  {name:"Dr. Suresh Jampa",role:"ASST.PROF.",dept:"ECE",campus:"HYD"},
  {name:"Dr. Pundareekam Goud Jakkapally",role:"ASST.PROF.",dept:"ECE",campus:"HYD"},
  {name:"Mr. Vinnakota Venu Balaji",role:"ASST.PROF.",dept:"ECE",campus:"HYD"}
,
  // ── MISSING FACULTY FROM PDF AY 2023-24 ──
  // CSE KLV Additional Asst Profs
  {name:"Ms. Arpita Roy",role:"ASST.PROF.",dept:"CSE",campus:"KLV"},
  {name:"Ms. S N Lakshmi Malluvalasa",role:"ASST.PROF.",dept:"CSE",campus:"KLV"},
  {name:"Mr. Vivek Kumar",role:"ASST.PROF.",dept:"CSE",campus:"KLV"},
  {name:"Mr. Gunti Surendra",role:"ASST.PROF.",dept:"CSE",campus:"KLV"},
  {name:"Mr. Karnati Raja Ram Mohan Rao",role:"ASST.PROF.",dept:"CSE",campus:"KLV"},
  {name:"Mr. V Ramesh Babu",role:"ASST.PROF.",dept:"CSE",campus:"KLV"},
  {name:"Mr. John Berkmans Thobiyas",role:"ASST.PROF.",dept:"CSE",campus:"KLV"},
  {name:"Ms. Pendem Swetha",role:"ASST.PROF.",dept:"CSE",campus:"KLV"},
  {name:"Mr. Saikat Samanta",role:"ASST.PROF.",dept:"CSE",campus:"KLV"},
  {name:"Mr. E Raveendra Reddy",role:"ASST.PROF.",dept:"CSE",campus:"KLV"},
  {name:"Mr. V Joe Nithin",role:"ASST.PROF.",dept:"CSE",campus:"KLV"},
  {name:"Mr. Bandaru Adithya Subrahmanyam",role:"ASST.PROF.",dept:"CSE",campus:"KLV"},
  {name:"Mr. Bekkanti Ashok",role:"ASST.PROF.",dept:"CSE",campus:"KLV"},
  {name:"Mr. Nellutla Ravinder",role:"ASST.PROF.",dept:"CSE",campus:"KLV"},
  {name:"Mr. V Deepak",role:"ASST.PROF.",dept:"CSE",campus:"KLV"},
  {name:"Mr. Dinesh R",role:"ASST.PROF.",dept:"CSE",campus:"KLV"},
  {name:"Ms. Dipanwita Debnath",role:"ASST.PROF.",dept:"CSE",campus:"KLV"},
  {name:"Mr. Naveen Mukkapati",role:"ASST.PROF.",dept:"CSE",campus:"KLV"},
  {name:"Mr. Mohd Shamsh Tabarej",role:"ASST.PROF.",dept:"CSE",campus:"KLV"},
  {name:"Mr. Penubaka Balaji",role:"ASST.PROF.",dept:"CSE",campus:"KLV"},
  {name:"Mr. S V Suresh Babu M",role:"ASST.PROF.",dept:"CSE",campus:"KLV"},
  {name:"Mr. Madhavarapu Chandan",role:"ASST.PROF.",dept:"CSE",campus:"KLV"},
  {name:"Mr. Mohan Kumar Chandol",role:"ASST.PROF.",dept:"CSE",campus:"KLV"},
  {name:"Mr. Jonnalagadda Surya Kiran",role:"ASST.PROF.",dept:"CSE",campus:"KLV"},
  {name:"Mr. Puvvada Nagesh",role:"ASST.PROF.",dept:"CSE",campus:"KLV"},
  {name:"Mr. Meduri Rajyalaxmi Prashanth",role:"ASST.PROF.",dept:"CSE",campus:"KLV"},
  {name:"Mr. Shaik Shaikshavali",role:"ASST.PROF.",dept:"CSE",campus:"KLV"},
  {name:"Mr. Kanakala V Ravi Teja",role:"ASST.PROF.",dept:"CSE",campus:"KLV"},
  {name:"Mr. Balajee R M",role:"ASST.PROF.",dept:"CSE",campus:"KLV"},
  {name:"Mr. Rajeev Kudari",role:"ASST.PROF.",dept:"CSE",campus:"KLV"},
  {name:"Mr. Shaik Mohammed Gouse",role:"ASST.PROF.",dept:"CSE",campus:"KLV"},
  {name:"Ms. Rani Medidha",role:"ASST.PROF.",dept:"CSE",campus:"KLV"},
  {name:"Mr. Feroz Khan",role:"ASST.PROF.",dept:"CSE",campus:"KLV"},
  {name:"Mr. Sreedhar Burada",role:"ASST.PROF.",dept:"CSE",campus:"KLV"},
  {name:"Ms. Vogirala Nandini",role:"ASST.PROF.",dept:"CSE",campus:"KLV"},
  {name:"Mr. T Krishnan",role:"ASST.PROF.",dept:"CSE",campus:"KLV"},
  {name:"Ms. Sai Durga Tejaswi Vinnakota",role:"ASST.PROF.",dept:"CSE",campus:"KLV"},
  {name:"Ms. Divya Chikati",role:"ASST.PROF.",dept:"CSE",campus:"KLV"},
  {name:"Mr. Pradeep Mani",role:"ASST.PROF.",dept:"CSE",campus:"KLV"},
  {name:"Mr. Palthiya Anantha Rao",role:"ASST.PROF.",dept:"CSE",campus:"KLV"},
  {name:"Mr. Rajesh Babu Gurindapalli",role:"ASST.PROF.",dept:"CSE",campus:"KLV"},
  {name:"Mr. Tushar Kanti De",role:"ASST.PROF.",dept:"CSE",campus:"KLV"},
  {name:"Ms. Guttikonda Prashanti",role:"ASST.PROF.",dept:"CSE",campus:"KLV"},
  {name:"Mr. Anantha Rao Gottimukkala",role:"ASST.PROF.",dept:"CSE",campus:"KLV"},
  {name:"Mr. Pottasiri Chandra Mohana Rai",role:"ASST.PROF.",dept:"CSE",campus:"KLV"},
  {name:"Ms. Amika Achom",role:"ASST.PROF.",dept:"CSE",campus:"KLV"},
  {name:"Mr. Dayanidhi Mohapatra",role:"ASST.PROF.",dept:"CSE",campus:"KLV"},
  {name:"Mr. John Dana Ebinezer Markapurapu",role:"ASST.PROF.",dept:"CSE",campus:"KLV"},
  {name:"Mr. Miriyala Markandeyulu",role:"ASST.PROF.",dept:"CSE",campus:"KLV"},
  {name:"Mr. Dineshnath Gopinath",role:"ASST.PROF.",dept:"CSE",campus:"KLV"},
  {name:"Mr. Rajesh Bingu",role:"ASST.PROF.",dept:"CSE",campus:"KLV"},
  {name:"Ms. Pasumarti Srilatha",role:"ASST.PROF.",dept:"CSE",campus:"KLV"},
  {name:"Mr. M Pandiyanathan",role:"ASST.PROF.",dept:"CSE",campus:"KLV"},
  {name:"Mr. P Murali Krishna",role:"ASST.PROF.",dept:"CSE",campus:"KLV"},
  {name:"Mr. P Dinesh Chandra",role:"ASST.PROF.",dept:"CSE",campus:"KLV"},
  {name:"Mr. Sukham Romen Singh",role:"ASST.PROF.",dept:"CSE",campus:"KLV"},
  {name:"Mr. A Somayajula",role:"ASST.PROF.",dept:"CSE",campus:"KLV"},
  {name:"Ms. M Uma Maheswari",role:"ASST.PROF.",dept:"CSE",campus:"KLV"},
  {name:"Ms. Sita Naga Venkata Jyotsnadevi Kosuru",role:"ASST.PROF.",dept:"CSE",campus:"KLV"},
  {name:"Mr. Yallamanda Rajesh Babu",role:"ASST.PROF.",dept:"CSE",campus:"KLV"},
  {name:"Mr. Bakkala Santha Kumar",role:"ASST.PROF.",dept:"CSE",campus:"KLV"},
  {name:"Mr. Lankoji Venkata Samba Siva Rao",role:"ASST.PROF.",dept:"CSE",campus:"KLV"},
  {name:"Mr. Mylapalli Srikanth",role:"ASST.PROF.",dept:"CSE",campus:"KLV"},
  {name:"Ms. Natha Priya",role:"ASST.PROF.",dept:"CSE",campus:"KLV"},
  {name:"Ms. Deepthi Natha",role:"ASST.PROF.",dept:"CSE",campus:"KLV"},
  {name:"Mr. S Mahesh Naidu",role:"ASST.PROF.",dept:"CSE",campus:"KLV"},
  {name:"Mr. Padamata Ramesh Babu",role:"ASST.PROF.",dept:"CSE",campus:"KLV"},
  {name:"Mr. Rekapalli Seetharam",role:"ASST.PROF.",dept:"CSE",campus:"KLV"},
  {name:"Mr. Gautam Hanumanthu",role:"ASST.PROF.",dept:"CSE",campus:"KLV"},
  {name:"Ms. Thella Preethi Priyanka",role:"ASST.PROF.",dept:"CSE",campus:"KLV"},
  {name:"Mr. Bandlamudi Arun Kumar",role:"ASST.PROF.",dept:"CSE",campus:"KLV"},
  {name:"Ms. Pamidimukkala Sai Geetha",role:"ASST.PROF.",dept:"CSE",campus:"KLV"},
  {name:"Mrs. Punyala Ramadevi",role:"ASST.PROF.",dept:"CSE",campus:"KLV"},
  {name:"Mr. Kuchipudi Prasanth Kumar",role:"ASST.PROF.",dept:"CSE",campus:"KLV"},
  {name:"Mr. Syed Mohammed Azmal",role:"ASST.PROF.",dept:"CSE",campus:"KLV"},
  {name:"Ms. Annamaraju Thanuja",role:"ASST.PROF.",dept:"CSE",campus:"KLV"},
  {name:"Mr. Mani Mohan Dupaty",role:"ASST.PROF.",dept:"CSE",campus:"KLV"},
  {name:"Ms. Yelisetty Madhavilatha",role:"ASST.PROF.",dept:"CSE",campus:"KLV"},
  {name:"Ms. Sarihaddu Kavitha",role:"ASST.PROF.",dept:"CSE",campus:"KLV"},
  {name:"Ms. Praneetha Alur",role:"ASST.PROF.",dept:"CSE",campus:"KLV"},
  {name:"Ms. Setti Rajeswari",role:"ASST.PROF.",dept:"CSE",campus:"KLV"},
  {name:"Mr. Kishore Dasari",role:"ASST.PROF.",dept:"CSE",campus:"KLV"},
  {name:"Ms. Anumula Sruthi",role:"ASST.PROF.",dept:"CSE",campus:"KLV"},
  {name:"Mr. K Selvam",role:"ASST.PROF.",dept:"CSE",campus:"KLV"},
  {name:"Mr. Jagan Mohan Srihaddu",role:"ASST.PROF.",dept:"CSE",campus:"KLV"},
  {name:"Mr. Rudra Mani Bhutia",role:"ASST.PROF.",dept:"CSE",campus:"KLV"},
  {name:"Mr. Yengala Amaraiah",role:"ASST.PROF.",dept:"CSE",campus:"KLV"},
  {name:"Mr. Jitender Ahuja",role:"ASST.PROF.",dept:"CSE",campus:"KLV"},
  {name:"Ms. Rajamahendravarapu Lakshmi Durga",role:"ASST.PROF.",dept:"CSE",campus:"KLV"},
  {name:"Mr. Bangaru Balakrishna",role:"ASST.PROF.",dept:"CSE",campus:"KLV"},
  {name:"Mr. Narasimha Swamy Lavudiya",role:"ASST.PROF.",dept:"CSE",campus:"KLV"},
  {name:"Ms. Gnana Deepthi Bitra",role:"ASST.PROF.",dept:"CSE",campus:"KLV"},
  {name:"Ms. Panguluri Mounica",role:"ASST.PROF.",dept:"CSE",campus:"KLV"},
  {name:"Ms. Chodavarapu L N Deepika",role:"ASST.PROF.",dept:"CSE",campus:"KLV"},
  {name:"Mr. Sornapudi Sandeep Kumar",role:"ASST.PROF.",dept:"CSE",campus:"KLV"},
  {name:"Mr. C M A K Zeelan Basha",role:"ASST.PROF.",dept:"CSE",campus:"KLV"},
  {name:"Mr. Sudarsa Dorababu",role:"ASST.PROF.",dept:"CSE",campus:"KLV"},
  {name:"Ms. Premalatha Velagapalli",role:"ASST.PROF.",dept:"CSE",campus:"KLV"},
  {name:"Mr. Amara S A L G Gopala Gupta",role:"ASST.PROF.",dept:"CSE",campus:"KLV"},
  {name:"Mr. E Rajesh Kumar",role:"ASST.PROF.",dept:"CSE",campus:"KLV"},
  {name:"Ms. Syed Karimunnisa",role:"ASST.PROF.",dept:"CSE",campus:"KLV"},
  {name:"Mr. T Ganesan",role:"ASST.PROF.",dept:"CSE",campus:"KLV"},
  {name:"Ms. U Harita",role:"ASST.PROF.",dept:"CSE",campus:"KLV"},
  {name:"Mr. Madupu Ram Kumar",role:"ASST.PROF.",dept:"CSE",campus:"KLV"},
  {name:"Ms. Parasa Gayathri",role:"ASST.PROF.",dept:"CSE",campus:"KLV"},
  {name:"Ms. Yamini Tondepu",role:"ASST.PROF.",dept:"CSE",campus:"KLV"},
  {name:"Mr. Konduri Sriraghu Praveen",role:"ASST.PROF.",dept:"CSE",campus:"KLV"},
  {name:"Mr. Agraharam Siva Kumar Reddy",role:"ASST.PROF.",dept:"CSE",campus:"KLV"},
  {name:"Ms. Poranki Vijaya Lakshmi Rama Naga Sai Sudha",role:"ASST.PROF.",dept:"CSE",campus:"KLV"},
  {name:"Ms. Chunduri Lavanya",role:"ASST.PROF.",dept:"CSE",campus:"KLV"},
  {name:"Mr. Shankar Prasad Mitra",role:"ASST.PROF.",dept:"CSE",campus:"KLV"},
  {name:"Ms. Pothula Hymavathi",role:"ASST.PROF.",dept:"CSE",campus:"KLV"},
  {name:"Mr. Chintalapudi Anil",role:"ASST.PROF.",dept:"CSE",campus:"KLV"},
  {name:"Ms. Alapati Smitha Kranthi",role:"ASST.PROF.",dept:"CSE",campus:"KLV"},
  {name:"Mr. Anantharamaiah Vengala",role:"ASST.PROF.",dept:"CSE",campus:"KLV"},
  {name:"Ms. Tanaya Ganguly",role:"ASST.PROF.",dept:"CSE",campus:"KLV"},
  {name:"Mr. Arumalla Nagaraju",role:"ASST.PROF.",dept:"CSE",campus:"KLV"},
  {name:"Ms. Manasa Adusumilli",role:"ASST.PROF.",dept:"CSE",campus:"KLV"},
  {name:"Mr. Dharmendra Kumar Pilli",role:"ASST.PROF.",dept:"CSE",campus:"KLV"},
  {name:"Mr. Manoj Kumar Padhi",role:"ASST.PROF.",dept:"CSE",campus:"KLV"},
  {name:"Ms. Inakollu Aswani",role:"ASST.PROF.",dept:"CSE",campus:"KLV"},
  {name:"Mr. Gandavadi Venkatesh",role:"ASST.PROF.",dept:"CSE",campus:"KLV"},
  {name:"Mr. Abhishek Gupta",role:"ASST.PROF.",dept:"CSE",campus:"KLV"},
  {name:"Mr. Karanki Naga Gopi",role:"ASST.PROF.",dept:"CSE",campus:"KLV"},
  {name:"Mr. Krupadanam Rayi",role:"ASST.PROF.",dept:"CSE",campus:"KLV"},
  {name:"Mr. Vudatha Bala Venkata Naga Krishna Suresh",role:"ASST.PROF.",dept:"CSE",campus:"KLV"},
  {name:"Mr. Padyala Priyadarsan",role:"ASST.PROF.",dept:"CSE",campus:"KLV"},
  {name:"Mr. Pallapati Ravikumar",role:"ASST.PROF.",dept:"CSE",campus:"KLV"},
  {name:"Mr. B Surendra Babu",role:"ASST.PROF.",dept:"CSE",campus:"KLV"},
  {name:"Mr. Komatigunta Nagaraju",role:"ASST.PROF.",dept:"CSE",campus:"KLV"},
  {name:"Mr. Nagineni Rajesh Babu",role:"ASST.PROF.",dept:"CSE",campus:"KLV"},
  {name:"Mr. Aravindan Srinivasan",role:"ASST.PROF.",dept:"CSE",campus:"KLV"},
  {name:"Mr. Thamodharan Arumugam",role:"ASST.PROF.",dept:"CSE",campus:"KLV"},
  {name:"Mr. Bhavanam Venkata Suresh Reddy",role:"ASST.PROF.",dept:"CSE",campus:"KLV"},
  {name:"Ms. Smritilekha Das",role:"ASST.PROF.",dept:"CSE",campus:"KLV"},
  {name:"Dr. Visamsetty Venkata Surya Sasank",role:"ASST.PROF.",dept:"CSE",campus:"KLV"},
  {name:"Dr. P Srinivasa Kumar",role:"ASST.PROF.",dept:"CSE",campus:"KLV"},
  {name:"Mr. Sonthi Vijaya Krishna",role:"ASST.PROF.",dept:"CSE",campus:"KLV"},
  {name:"Mr. Bejjam Surendranadh Benarji",role:"ASST.PROF.",dept:"CSE",campus:"KLV"},
  {name:"Mr. Altaf Ismail Karani",role:"ASST.PROF.",dept:"CSE",campus:"KLV"},
  {name:"Ms. Babu Keerthi Samhitha",role:"ASST.PROF.",dept:"CSE",campus:"KLV"},
  {name:"Mr. Penumacha Vikram",role:"ASST.PROF.",dept:"CSE",campus:"KLV"},
  {name:"Mr. Nyakapu Rajender",role:"ASST.PROF.",dept:"CSE",campus:"KLV"},
  {name:"Ms. Nuthakki Praveena",role:"ASST.PROF.",dept:"CSE",campus:"KLV"},
  {name:"Ms. Ganugapati Naga Sowjanya",role:"ASST.PROF.",dept:"CSE",campus:"KLV"},
  {name:"Mr. Rodda Dilip Kumar",role:"ASST.PROF.",dept:"CSE",campus:"KLV"},
  {name:"Ms. Vemula Jasmine Sowmya",role:"ASST.PROF.",dept:"CSE",campus:"KLV"},
  {name:"Ms. Govindu Komali",role:"ASST.PROF.",dept:"CSE",campus:"KLV"},
  {name:"Mr. Kavuri Sreekanth",role:"ASST.PROF.",dept:"CSE",campus:"KLV"},
  {name:"Mr. S Saravanan",role:"ASST.PROF.",dept:"CSE",campus:"KLV"},
  {name:"Dr. Bhimavarapu John Philip",role:"ASST.PROF.",dept:"CSE",campus:"KLV"},
  {name:"Ms. G Swapna",role:"ASST.PROF.",dept:"CSE",campus:"KLV"},
  {name:"Dr. Narayanam V Siva Kumari",role:"ASST.PROF.",dept:"CSE",campus:"KLV"},
  {name:"Dr. Tiruthamara Seshaiyer Rajeswari",role:"ASST.PROF.",dept:"CSE",campus:"KLV"},
  {name:"Mr. Debabrata Hazra",role:"ASST.PROF.",dept:"CSE",campus:"KLV"},
  {name:"Mr. Divvela Surendra",role:"ASST.PROF.",dept:"CSE",campus:"KLV"},
  {name:"Ms. Rayapudi E M Prema Chandrika",role:"ASST.PROF.",dept:"CSE",campus:"KLV"},
  {name:"Mr. Gattupalli Subhakara Rao",role:"ASST.PROF.",dept:"CSE",campus:"KLV"},
  {name:"Ms. Sridevi Sakhamuri",role:"ASST.PROF.",dept:"CSE",campus:"KLV"},
  {name:"Ms. Gogineni Anusha",role:"ASST.PROF.",dept:"CSE",campus:"KLV"},
  {name:"Ms. Abha Tripathi",role:"ASST.PROF.",dept:"CSE",campus:"KLV"},
  {name:"Dr. Tumuluri Kanthimathi",role:"ASST.PROF.",dept:"CSE",campus:"KLV"},
  {name:"Dr. Kruthiventi Sai Sarath",role:"ASST.PROF.",dept:"CSE",campus:"KLV"},
  {name:"Dr. Panchakarla N V Balasubramanyam",role:"ASST.PROF.",dept:"CSE",campus:"KLV"},
  {name:"Dr. Lokesh Kalapala",role:"ASST.PROF.",dept:"CSE",campus:"KLV"},
  {name:"Dr. M V V K Srinivas Prasad",role:"ASST.PROF.",dept:"CSE",campus:"KLV"},
  {name:"Dr. M Gnana Kiran",role:"ASST.PROF.",dept:"CSE",campus:"KLV"},
  {name:"Dr. A Venkateswara Rao",role:"ASST.PROF.",dept:"CSE",campus:"KLV"},
  {name:"Dr. Sk Babu",role:"ASST.PROF.",dept:"CSE",campus:"KLV"},
  {name:"Dr. S Shanmugan",role:"ASST.PROF.",dept:"CSE",campus:"KLV"},
  // Mechanical Engineering extras
  {name:"Mr. A V Siva Ram Prasad",role:"ASSOC.PROF.",dept:"Mechanical Engineering",campus:"KLV"},
  {name:"Mr. Buragadda Kiran Kumar",role:"ASSOC.PROF.",dept:"Mechanical Engineering",campus:"KLV"},
  {name:"Mr. Guntuku Raja Sanjay Krishna",role:"ASSOC.PROF.",dept:"Mechanical Engineering",campus:"KLV"},
  // School of Law extras
  {name:"Ms. Moutushi Thakur",role:"ASST.PROF.",dept:"School of Law",campus:"KLV"},
  {name:"Ms. Noopur Agarwal",role:"ASST.PROF.",dept:"School of Law",campus:"KLV"},
  {name:"Ms. Chandini Chowdary R",role:"ASST.PROF.",dept:"School of Law",campus:"KLV"},
  {name:"Mr. Vemuru Leela Krishna",role:"ASST.PROF.",dept:"School of Law",campus:"KLV"},
  {name:"Mr. Mudassir Rasoolwani",role:"ASST.PROF.",dept:"School of Law",campus:"KLV"},
  {name:"Ms. Keya Sarkar",role:"ASST.PROF.",dept:"School of Law",campus:"KLV"},
  {name:"Mr. Mohd Hammaad Siddiqui",role:"ASST.PROF.",dept:"School of Law",campus:"KLV"},
  {name:"Ms. Bhargavi Mannava",role:"ASST.PROF.",dept:"School of Law",campus:"KLV"},
  {name:"Mr. Avirineni Venkata Subrahmanyam",role:"ASST.PROF.",dept:"School of Law",campus:"KLV"},
  // Pharmacy extras
  {name:"Ms. Lokeswari Pinneboyana",role:"ASST.PROF.",dept:"Pharmacy",campus:"KLV"},
  {name:"Ms. Nallapaty Sri Lakshmi",role:"ASST.PROF.",dept:"Pharmacy",campus:"KLV"},
  {name:"Mr. Alla Narayana Rao",role:"ASST.PROF.",dept:"Pharmacy",campus:"KLV"},
  {name:"Mr. Md Jahasultana",role:"ASST.PROF.",dept:"Pharmacy",campus:"KLV"},
  {name:"Ms. T Prasanna Kumari",role:"ASST.PROF.",dept:"Pharmacy",campus:"KLV"},
  {name:"Ms. Nakka Venkata Naga Jyothi",role:"ASST.PROF.",dept:"Pharmacy",campus:"KLV"},
  {name:"Ms. Lanka Haritha",role:"ASST.PROF.",dept:"Pharmacy",campus:"KLV"},
  {name:"Ms. Gurnani Haritha",role:"ASST.PROF.",dept:"Pharmacy",campus:"KLV"},
  {name:"Mr. Narayana Murthy Ganta",role:"ASST.PROF.",dept:"Pharmacy",campus:"KLV"},
  {name:"Mr. Thathapudi Daveedu",role:"ASST.PROF.",dept:"Pharmacy",campus:"KLV"},
  // ECE KLV extras
  {name:"Dr. Shubhro",role:"ASSOC.PROF.",dept:"ECE",campus:"KLV"},
  {name:"Mr. A V Prabhu",role:"ASSOC.PROF.",dept:"ECE",campus:"KLV"},
  {name:"Mr. Suresh Namgiri",role:"ASSOC.PROF.",dept:"ECE",campus:"KLV"},
  {name:"Mr. Koganti Sripath Roy",role:"ASST.PROF.",dept:"ECE",campus:"KLV"},
  {name:"Ms. Jagupalli Lakshmi Prasanna",role:"ASST.PROF.",dept:"ECE",campus:"KLV"},
  {name:"Mr. Thalapaneni Penchala Naidu",role:"ASST.PROF.",dept:"ECE",campus:"KLV"},
  {name:"Mr. Muthabathula Lakshmana Kumar",role:"ASST.PROF.",dept:"ECE",campus:"KLV"},
  {name:"Mr. Badita Kali Vara Prasad",role:"ASST.PROF.",dept:"ECE",campus:"KLV"},
  {name:"Mr. R Agilesh Saravanan",role:"ASST.PROF.",dept:"ECE",campus:"KLV"},
  {name:"Mr. Palagani Srikanth Reddy",role:"ASST.PROF.",dept:"ECE",campus:"KLV"},
  {name:"Mr. K Suresh Kumar",role:"ASST.PROF.",dept:"ECE",campus:"KLV"},
  {name:"Mr. Ch Bhupathi",role:"ASST.PROF.",dept:"ECE",campus:"KLV"},
  {name:"Mr. T P S Kumar Kusumanchi",role:"ASST.PROF.",dept:"ECE",campus:"KLV"},
  // Hyderabad extras
  {name:"Mr. Harish G V",role:"ASST.PROF.",dept:"CSE",campus:"HYD"},
  {name:"Ms. Mukesh Eknath Mankar",role:"ASST.PROF.",dept:"CSE",campus:"HYD"},
  {name:"Mr. K J Gouthaman",role:"ASST.PROF.",dept:"CSE",campus:"HYD"},
  {name:"Ms. Alisha Baglari",role:"ASST.PROF.",dept:"CSE",campus:"HYD"},
  {name:"Ms. Vidhi Vats",role:"ASST.PROF.",dept:"CSE",campus:"HYD"},
  {name:"Ms. Atisha Rai",role:"ASST.PROF.",dept:"CSE",campus:"HYD"},

];

// ══════════════════════════════════════════════════════════════
// getFacultyChatSummary()
// Used by CHAT SESSION ONLY — returns counts, not names
// ══════════════════════════════════════════════════════════════
function getFacultyChatSummary(query) {
  const q = query.toLowerCase();

  // Detect department from query
  const deptMap = {
    'cse': 'CSE',
    'computer science': 'CSE',
    'ece': 'ECE',
    'electronics': 'ECE',
    'eee': 'EEE',
    'electrical': 'EEE',
    'mechanical': 'Mechanical Engineering',
    'mech': 'Mechanical Engineering',
    'civil': 'Civil Engineering',
    'biotech': 'Biotechnology',
    'biotechnology': 'Biotechnology',
    'pharmacy': 'Pharmacy',
    'business': 'Business School',
    'mba': 'Business School',
    'bba': 'Business School',
    'architecture': 'Architecture',
    'arch': 'Architecture',
    'law': 'School of Law',
    'agriculture': 'Agriculture',
    'agri': 'Agriculture',
    'maths': 'Mathematics',
    'mathematics': 'Mathematics',
    'physics': 'Physics',
    'chemistry': 'Chemistry',
    'computer applications': 'Computer Applications',
    'mca': 'Computer Applications',
    'bca': 'Computer Applications'
  };

  // Detect campus
  const campusFilter = q.includes('hyderabad') || q.includes('hyd') ? 'HYD'
    : q.includes('vijayawada') || q.includes('klv') ? 'KLV'
    : 'all';

  // Find matching dept
  let matchedDept = null;
  for (const [keyword, dept] of Object.entries(deptMap)) {
    if (q.includes(keyword)) { matchedDept = dept; break; }
  }

  if (matchedDept) {
    // Filter by dept and campus
    let members = FAC_DATA.filter(f => f.dept === matchedDept);
    if (campusFilter !== 'all') members = members.filter(f => f.campus === campusFilter);

    const profs  = members.filter(f => f.role === 'PROFESSOR').length;
    const assoc  = members.filter(f => f.role === 'ASSOC.PROF.').length;
    const asst   = members.filter(f => f.role === 'ASST.PROF.').length;
    const total  = members.length;
    const campus = campusFilter === 'all' ? 'Vijayawada + Hyderabad'
      : campusFilter === 'KLV' ? 'Vijayawada' : 'Hyderabad';

    return `${matchedDept} Department (${campus}): ${total} faculty — ${profs} Professors, ${assoc} Associate Professors, ${asst} Assistant Professors. Check the Faculty tab for full directory with search & filter.`;
  }

  // No specific dept — give overall summary
  const total = FAC_DATA.length;
  const depts = [...new Set(FAC_DATA.map(f => f.dept))].length;
  const profs = FAC_DATA.filter(f => f.role === 'PROFESSOR').length;
  return `KLU has ${total}+ faculty across ${depts} departments (Vijayawada + Hyderabad campuses) — ${profs}+ Professors. Check the Faculty tab for complete directory with search & filter by campus, department and role!`;
}